//		Alpine Spew Bastards		//

Class Dcx_SurferMutant1 : Doomimp
{
	Default
	{
		SeeSound "Surfer1/Sight";
		PainSound "Surfer1/Pain";
		DeathSound "Surfer1/Death";
		ActiveSound "Surfer1/Active";
		Tag "Red Surfer Mutant";
		HitObituary "%o was pwned by a Red Surfer Mutant";
		Obituary "%o was spewed by a Red Surfer Mutant";
	}
	
	void A_SpewAttack()
	{
		A_CustomComboAttack("Dcx_BallOSpew", 32, 3 * random(1, 8), "baron/melee");
		A_FaceTarget();
	}
	
	States
	{
	Spawn:
		SFM1 AB 10 A_Look;
		Loop;
	See:
		SFM1 AABBCCDD 3 A_Chase;
		Loop;
	Melee:
	Missile:
		SFM1 EF 8 A_FaceTarget;
		SFM1 G 6 A_SpewAttack();
		Goto See;
	Pain:
		SFM1 H 2;
		SFM1 H 2 A_Pain;
		Goto See;
	Death:
		SFM1 I 8;
		SFM1 J 8 A_Scream;
		SFM1 K 6;
		SFM1 L 6 A_NoBlocking;
		SFM1 M -1;
		Stop;
	XDeath:
		SFM1 N 5;
		SFM1 O 5 A_XScream;
		SFM1 P 5;
		SFM1 Q 5 A_NoBlocking;
		SFM1 RST 5;
		SFM1 U -1;
		Stop;
	Raise:
		SFM1 MLKJI 8;
		Goto See;
	}
}

Class Dcx_BallOSpew : DoomImpBall
{
	Default
	{
		SeeSound "Spewball/Shot";
		DeathSound "Spewball/ShotX";
	}
	States
	{
	Spawn:
		BOSW AB 4 BRIGHT;
		Loop;
	Death:
		BOSW CDE 6 BRIGHT;
		Stop;
	}
}

Class Dcx_SurferMutant2 : Shotgunguy 
{
	Default
	{
		SeeSound "Surfer2/Sight";
		AttackSound "shotguy/attack";
		PainSound "Surfer2/Pain";
		DeathSound "Surfer2/Death";
		ActiveSound "Surfer2/Active";
		Obituary "%o was blasted by a Yellow Surfer Mutant";
		Tag "Yellow Surfer Mutant";
		DropItem "Shotgun";
	}
	States
	{
	Spawn:
		SFM2 AB 10 A_Look;
		Loop;
	See:
		SFM2 AABBCCDD 3 A_Chase;
		Loop;
	Missile:
		SFM2 E 10 A_FaceTarget;
		SFM2 F 10 BRIGHT A_SposAttackUseAtkSound;
		SFM2 E 10;
		Goto See;
	Pain:
		SFM2 G 3;
		SFM2 G 3 A_Pain;
		Goto See;
	Death:
		SFM2 H 5;
		SFM2 I 5 A_Scream;
		SFM2 J 5 A_NoBlocking;
		SFM2 K 5;
		SFM2 L -1;
		Stop;
	XDeath:
		SFM2 M 5;
		SFM2 N 5 A_XScream;
		SFM2 O 5 A_NoBlocking;
		SFM2 PQRST 5;
		SFM2 U -1;
		Stop;
	Raise:
		SFM2 L 5;
		SFM2 KJIH 5;
		Goto See;
	}
}

Class Dcx_LoungeSinger : Demon 
{
	Default
	{
		SeeSound "Singer/Sight";
		AttackSound "Singer/Melee";
		PainSound "Singer/pain";
		DeathSound "Singer/death";
		ActiveSound "Singer/active";
		Obituary "%o was sung to death by a Lounge Singer";
		Tag "Lounge Singer";
	}
	States
	{
	Spawn:
		SNGR AB 10 A_Look;
		Loop;
	See:
		SNGR AABBCCDD 2 Fast A_Chase;
		Loop;
	Melee:
		SNGR EF 8 Fast A_FaceTarget;
		SNGR G 8 Fast A_SargAttack;
		Goto See;
	Pain:
		SNGR H 2 Fast;
		SNGR H 2 Fast A_Pain;
		Goto See;
	Death:
		SNGR I 8;
		SNGR J 8 A_Scream;
		SNGR K 4;
		SNGR L 4 A_NoBlocking;
		SNGR M 4;
		SNGR N -1;
		Stop;
	Raise:
		SNGR N 5;
		SNGR MLKJI 5;
		Goto See;
	}
}

Class Dcx_SpectreSinger : Dcx_LoungeSinger
{
	Default
	{
		+SHADOW
		RenderStyle "OptFuzzy";
		Alpha 0.5;
	}
}

Class Dcx_NightmareSinger : Dcx_LoungeSinger
{
	Default
	{
		Health 300;
		+SHADOW
		RenderStyle "Subtract";
		BloodColor "Blue";
	}
}

Class Dcx_BottleOfSpew : Lostsoul 
{
	Default
	{
		Obituary "%o was eaten by a bottle of Spew";
		Tag "Bottle of Alpine Spew^tm";
		DeathSound "Spewball/ShotX";
	}
	States
	{
	Spawn:
		SPWB AB 10 BRIGHT A_Look;
		Loop;
	See:
		SPWB AB 6 BRIGHT A_Chase;
		Loop;
	Missile:
		SPWB C 10 BRIGHT A_FaceTarget;
		SPWB D 4 BRIGHT A_SkullAttack;
		SPWB CD 4 BRIGHT;
		Goto Missile+2;
	Pain:
		SPWB E 3 BRIGHT;
		SPWB E 3 BRIGHT A_Pain;
		Goto See;
	Death:
		SPWB F 6 BRIGHT;
		SPWB G 6 BRIGHT A_Scream;
		SPWB H 6 BRIGHT;
		SPWB I 6 BRIGHT A_NoBlocking;
		SPWB J 6;
		SPWB K 6;
		Stop;
	}
}

Class Dcx_GiantCanOfSpew : SpiderMastermind 
{
	Default
	{
		Obituary "%o was downed by a can of Alpine Spew^tm";
		Tag "Giant can of Alpine Spew";
	}
	States
	{
	Spawn:
		COAS AB 10 A_Look;
		Loop;
	See:
		COAS A 3 A_Metal;
		COAS ABB 3 A_Chase;
		COAS C 3 A_Metal;
		COAS CDD 3 A_Chase;
		COAS E 3 A_Metal;
		COAS EFF 3 A_Chase;
		Loop;
	Missile:
		COAS A 20 A_FaceTarget  ;
		COAS G 4 BRIGHT A_SPosAttackUseAtkSound;
		COAS H 4 BRIGHT A_SposAttackUseAtkSound;
		COAS H 1 BRIGHT A_SpidRefire;
		Goto Missile+1;
	Pain:
		COAS I 3;
		COAS I 3 A_Pain;
		Goto See;
	Death:
		COAS J 20 A_Scream;
		COAS K 10 A_NoBlocking;
		COAS LMNOPQRS 10 bright;
		TNT1 A 20;
		TNT1 A 0 A_BossDeath;
		Stop;
	}
}

Class Dcx_Kick_Column : Column
{
	States
	{
	Spawn:
		KCOL A -1 BRIGHT;
		Stop;
	}
}

Class Dcx_Kick_TechPillar : TechPillar
{
	States
	{
	Spawn:
		KELC A -1;
		Stop;
	}
}

Class Dcx_Kick_TechLamp : TechLamp
{
	States
	{
	Spawn:
		KTLP ABCD 4 BRIGHT;
		Loop;
	}
}