
Class Stimpack_BFG : Stimpack 
{
	States
	{
	Spawn:
		STIM B -1;
		Stop;
	}
}

Class Medikit_BFG : Medikit 
{
	States
	{
	Spawn:
		MEDI B -1;
		Stop;
	}
}

Class Berserk_BFG : Berserk 
{
	States
	{
	Spawn:
		PSTR B -1 bright;
		Stop;
	}
}

Class Stimpack_Unity : Stimpack 
{
	States
	{
	Spawn:
		STIM C -1;
		Stop;
	}
}

Class Medikit_Unity : Medikit 
{
	States
	{
	Spawn:
		MEDI C -1;
		Stop;
	}
}

Class Berserk_Unity : Berserk 
{
	States
	{
	Spawn:
		PSTR C -1 bright;
		Stop;
	}
}

Class Stimpack_Eternal : Stimpack 
{
	States
	{
	Spawn:
		STIM D -1;
		Stop;
	}
}

Class Medikit_Eternal : Medikit 
{
	States
	{
	Spawn:
		MEDI D -1;
		Stop;
	}
}

Class Berserk_Eternal : Berserk 
{
	States
	{
	Spawn:
		PSTR D -1 bright;
		Stop;
	}
}

Class Stimpack_rpg : Stimpack 
{
	States
	{
	Spawn:
		STIM E -1;
		Stop;
	}
}

Class Medikit_rpg : Medikit 
{
	States
	{
	Spawn:
		MEDI E -1;
		Stop;
	}
}

Class Berserk_rpg : Berserk 
{
	States
	{
	Spawn:
		PSTR E -1 bright;
		Stop;
	}
}

Class Stimpack_Kick : Stimpack 
{
	States
	{
	Spawn:
		KAMK A -1;
		Stop;
	}
}

Class Medikit_Kick : Medikit
{
	States
	{
	Spawn:
		KAMK B -1;
		Stop;
	}
}

Class Berserk_Kick : Berserk
{
	States
	{
	Spawn:
		KAMK C -1;
		Stop;
	}
}

class Clip_Kick : Clip
{
	States
	{
	Spawn:
		KAAM A -1;
		Stop;
	}
}

class ClipBox_Kick : ClipBox
{
	States
	{
	Spawn:
		KAAM B -1;
		Stop;
	}
}

class Shell_Kick : Shell
{
	States
	{
	Spawn:
		KAAM C -1;
		Stop;
	}
}

class ShellBox_Kick : ShellBox
{
	States
	{
	Spawn:
		KAAM D -1;
		Stop;
	}
}

class RocketAmmo_Kick : RocketAmmo
{
	States
	{
	Spawn:
		KAAM E -1;
		Stop;
	}
}

class RocketBox_Kick : RocketBox
{
	States
	{
	Spawn:
		KAAM F -1;
		Stop;
	}
}

class Cell_Kick : Cell
{
	States
	{
	Spawn:
		KAAM G -1;
		Stop;
	}
}

class CellPack_Kick : CellPack
{
	States
	{
	Spawn:
		KAAM H -1;
		Stop;
	}
}

class BlueCard_Kick : CustomInventory
{
	Default
	{
		Inventory.Pickupmessage "$GOTBLUECARD";
		Tag "$TAG_BLUECARD";
	}
	States
	{
	Spawn:
		KAKY A 10;
		KAKY B 10 bright;
		loop;
	Pickup:
		TNT1 A 0 A_GiveInventory("BlueCard");
		Stop;
	}
}

class YellowCard_Kick : CustomInventory
{
	Default
	{
		Inventory.Pickupmessage "$GOTYELWCARD";
		Tag "$TAG_YELLOWCARD";
	}
	States
	{
	Spawn:
		KAKY C 10;
		KAKY D 10 bright;
		loop;
	Pickup:
		TNT1 A 0 A_GiveInventory("YellowCard");
		Stop;
	}
}

class RedCard_Kick : CustomInventory
{
	Default
	{
		Inventory.Pickupmessage "$GOTREDCARD";
		Tag "$TAG_REDCARD";
	}
	States
	{
	Spawn:
		KAKY E 10;
		KAKY F 10 bright;
		loop;
	Pickup:
		TNT1 A 0 A_GiveInventory("RedCard");
		Stop;
	}
}

Class KickSodaCan : HealthBonus
{
	States
	{
	Spawn:
		SODA ABCDCB 6;
		Loop;
	}
}

Class KickArmorBonus : ArmorBonus
{
	States
	{
	Spawn:
		KAB2 ABCDCB 6;
		Loop;
	}
}

Class SoulSphere_Kick : SoulSphere
{
	States
	{
	Spawn:
		KSOL ABCDCB 6 Bright;
		Loop;
	}
}

Class MasterLevelsCompleted : Inventory
{
	Default
	{
		+INVENTORY.PERSISTENTPOWER
		+INVENTORY.UNCLEARABLE
		+INVENTORY.QUIET
		+INVENTORY.UNTOSSABLE
		Inventory.MaxAmount 5;
	}
}

Class AlreadyCompletedInferno : Inventory
{
	Default
	{
		+INVENTORY.PERSISTENTPOWER
		+INVENTORY.UNCLEARABLE
		+INVENTORY.QUIET
		+INVENTORY.UNTOSSABLE
		Inventory.MaxAmount 1;
	}
}

Class AlreadyCompletedTitan : Inventory
{
	Default
	{
		+INVENTORY.PERSISTENTPOWER
		+INVENTORY.UNCLEARABLE
		+INVENTORY.QUIET
		+INVENTORY.UNTOSSABLE
		Inventory.MaxAmount 1;
	}
}

Class AlreadyCompletedCabal : Inventory
{
	Default
	{
		+INVENTORY.PERSISTENTPOWER
		+INVENTORY.UNCLEARABLE
		+INVENTORY.QUIET
		+INVENTORY.UNTOSSABLE
		Inventory.MaxAmount 1;
	}
}

Class AlreadyCompletedTech : Inventory
{
	Default
	{
		+INVENTORY.PERSISTENTPOWER
		+INVENTORY.UNCLEARABLE
		+INVENTORY.QUIET
		+INVENTORY.UNTOSSABLE
		Inventory.MaxAmount 1;
	}
}

Class AlreadyCompletedLost : Inventory
{
	Default
	{
		+INVENTORY.PERSISTENTPOWER
		+INVENTORY.UNCLEARABLE
		+INVENTORY.QUIET
		+INVENTORY.UNTOSSABLE
		Inventory.MaxAmount 1;
	}
}


class DCX_JAGHealthbonus : Healthbonus
{
	Default
	{
	   Inventory.Amount 2;
	}
}

class DCX_JAGArmorbonus : Armorbonus
{
	Default
	{
	   Armor.Saveamount 2;
	}
}