
Extend Class DCX_EventHandler
{
	void TallSkyReplacements()
	{
			String SkyName = TexMan.GetName(level.skytexture1);
			String mapPrefix = level.MapName.Left(3);
			mapPrefix = mapPrefix.MakeLower();
			String mapName = level.MapName.MakeLower();
			
			if ( SkyName == "DSKY1" && !( (mapPrefix == "e1m" ) && CVar.FindCVar("dcx_TextureEchancements").GetBool() == true ) )
			Level.ChangeSky(TexMan.CheckForTexture("DSKY1TALL"), TexMan.CheckForTexture("DSKY1TALL"));
			if ( SkyName == "USKY1" )
			Level.ChangeSky(TexMan.CheckForTexture("USKY1TALL"), TexMan.CheckForTexture("USKY1TALL"));
			if ( SkyName == "DSKY2" && !( (mapPrefix == "e2m" ) && CVar.FindCVar("dcx_TextureEchancements").GetBool() == true ))
			Level.ChangeSky(TexMan.CheckForTexture("DSKY2TALL"), TexMan.CheckForTexture("DSKY2TALL"));
			if ( SkyName == "USKY2" )
			Level.ChangeSky(TexMan.CheckForTexture("USKY2TALL"), TexMan.CheckForTexture("USKY2TALL"));
			if ( SkyName == "DSKY3" && ( CVar.FindCVar("dcx_TextureEchancements").GetBool() != true ))//&& !( ( mapPrefix == "e3m" || mapName.Left(5) == "psx02" ) && CVar.FindCVar("fs_toggle").GetBool() == true ))
			Level.ChangeSky(TexMan.CheckForTexture("DSKY3TALL"), TexMan.CheckForTexture("DSKY3TALL"));
			if ( SkyName == "USKY3" )
			Level.ChangeSky(TexMan.CheckForTexture("USKY3TALL"), TexMan.CheckForTexture("USKY3TALL"));
			if ( SkyName == "SKY4" )
			Level.ChangeSky(TexMan.CheckForTexture("DSKY4TALL"), TexMan.CheckForTexture("SKY4TALL"));
			if ( SkyName == "SKY1" )
			Level.ChangeSky(TexMan.CheckForTexture("RSKY1TALL"), TexMan.CheckForTexture("SKY1TALL"));
			if ( SkyName == "SKY2" )
			Level.ChangeSky(TexMan.CheckForTexture("RSKY2TALL"), TexMan.CheckForTexture("SKY2TALL"));
			if ( SkyName == "SKY3" )
			Level.ChangeSky(TexMan.CheckForTexture("RSKY3TALL"), TexMan.CheckForTexture("SKY3TALL"));
			if ( SkyName == "MSKY1" )
			Level.ChangeSky(TexMan.CheckForTexture("rsky6tal"), TexMan.CheckForTexture("rsky6tal"));
			if ( SkyName == "TSKY1" )
			Level.ChangeSky(TexMan.CheckForTexture("TSKY1TALL"), TexMan.CheckForTexture("TSKY1TALL"));
			if ( SkyName == "TSKY2" )
			Level.ChangeSky(TexMan.CheckForTexture("TSKY2TALL"), TexMan.CheckForTexture("TSKY2TALL"));
			if ( SkyName == "TSKY3" )
			Level.ChangeSky(TexMan.CheckForTexture("TSKY3TALL"), TexMan.CheckForTexture("TSKY3TALL"));
			if ( SkyName == "PSKY1" )
			Level.ChangeSky(TexMan.CheckForTexture("PSKY1TALL"), TexMan.CheckForTexture("PSKY1TALL"));
			if ( SkyName == "PSKY2" )
			Level.ChangeSky(TexMan.CheckForTexture("PSKY2TALL"), TexMan.CheckForTexture("PSKY2TALL"));
			if ( SkyName == "PSKY3" )
			Level.ChangeSky(TexMan.CheckForTexture("PSKY3TALL"), TexMan.CheckForTexture("PSKY3TALL"));
	}

    void TextureEnchancements()
    {
		bool skyEnable   = CVar.FindCVar("uw_sky_enable").GetBool();
		String SkyName = TexMan.GetName(level.skytexture1);
        String mapPrefix = level.MapName.Left(3);
        mapPrefix = mapPrefix.MakeLower();
		String mapName = level.MapName.MakeLower();
		
		//Animated Computer Textures
		if ( mapName.left(3) != "pt_" )
		{
			if ( mapName != "dz_map32" )
			Level.ReplaceTextures("COMPSTA1", "COMPSAN1", 0);
		}
		
		if ( mapName != "dz_map32" )
		Level.ReplaceTextures("COMPSTA2", "COMPSA21", 0);
		
		if ( mapName != "map08" )
		{
			if ( mapName != "ml_map22" )
			{
				if ( mapName != "dz_map32" )
				{
					Level.ReplaceTextures("SPACEW3",  "TVSNOW01", 0);
					Level.ReplaceTextures("COMTAL02",  "TVSNOW01", 0);
				}
			}
		}
		
		if ( mapName != "dz_map32" )
		{
			Level.ReplaceTextures("COMPUTE1",  "COMPUT12",0);
			Level.ReplaceTextures("COMPUTE2",  "COMPUT22",0);
			Level.ReplaceTextures("COMPUTE3",  "COMPUT32",0);
		}
		
		if ( mapName.left(3) != "ja_" )
		{
			if ( mapName != "dz_map32" )
			Level.ReplaceTextures("COMPTALL",  "COMPTAL1",0);
		}
		
		if ( mapName != "dz_map32" )
		{
			Level.ReplaceTextures("COMP2", 	   "COMP2ON1",0);
			Level.ReplaceTextures("SILVER3",   "SILVER32",0);
		}
		
		if ( (mapName == "ml_map19") 
		  || (mapName == "ml_map37") 
		  || (mapName == "ml_map38") 
		  || (mapName == "ml_map39")
		  || (mapName == "ml_map20")
		  || (mapName == "ml_map40"))
		{
			Level.ChangeSky(TexMan.CheckForTexture("PSKY2",TexMan.Type_Any),TexMan.CheckForTexture("PSKY2",TexMan.Type_Any));
			if ( skyEnable )
			{ TallSkyReplacements(); }
		}	
		if ( (mapName == "ml_map41")
		  || (mapName == "ml_map42"))
		{
			Level.ChangeSky(TexMan.CheckForTexture("USKY3",TexMan.Type_Any),TexMan.CheckForTexture("USKY3",TexMan.Type_Any));
			if ( skyEnable )
			{ TallSkyReplacements(); }
		}
		if ( (mapName == "ml_map10") || (mapName == "ml_map43") )
			Level.ChangeSky(TexMan.CheckForTexture("SKY3TALS",TexMan.Type_Any),TexMan.CheckForTexture("SKY3TALS",TexMan.Type_Any));
		
		if ( (mapName == "tn_map25") || (mapName == "tn_map26") || (mapName == "tn_map27") || (mapName == "tn_map28") )
			Level.ChangeSky(TexMan.CheckForTexture("SKY3TALS",TexMan.Type_Any),TexMan.CheckForTexture("SKY3TALS",TexMan.Type_Any));
		
		if ( SkyName == "DSKY1" )
		{
			if (   mapName.left(2) == "e1"
				|| mapName.left(5) == "cs_e1" 
				|| mapName.left(5) == "ch_e1" 
				|| mapName.left(5) == "co_e1" )
			{
				Level.ReplaceTextures("DSKY1", "USKY1", 0);
				Level.ChangeSky(TexMan.CheckForTexture("USKY1",TexMan.Type_Any),TexMan.CheckForTexture("USKY1",TexMan.Type_Any));
				if ( skyEnable )
				{ TallSkyReplacements(); }
			}
		}
		
		if ( SkyName == "DSKY2" )
		{
			if (   mapName.left(2) == "e2"
				|| mapName.left(5) == "cs_e2" 
				|| mapName.left(5) == "ch_e2" 
				|| mapName.left(5) == "co_e2" )
			{
				Level.ReplaceTextures("DSKY2", "USKY2", 0);
				Level.ChangeSky(TexMan.CheckForTexture("USKY2",TexMan.Type_Any),TexMan.CheckForTexture("USKY2",TexMan.Type_Any));
				if ( skyEnable )
				{ TallSkyReplacements(); }
			}
		}
		
		if ( SkyName == "DSKY3" )
		{
			Level.ReplaceTextures("DSKY3", "USKY3", 0);
			Level.ChangeSky(TexMan.CheckForTexture("USKY3",TexMan.Type_Any),TexMan.CheckForTexture("USKY3",TexMan.Type_Any));
			if ( skyEnable )
			{ TallSkyReplacements(); }
		}
				
		if ( (mapPrefix == "nv_") )
		{
			if ( (mapName == "nv_map01") || (mapName == "nv_map02") )
			{
				Level.ChangeSky(TexMan.CheckForTexture("SKY2",TexMan.Type_Any),TexMan.CheckForTexture("SKY2",TexMan.Type_Any));
				if ( skyEnable )
				{ TallSkyReplacements(); }
			}
		}	
		
		if ( mapName == "tn_map31")
		{
			Level.ChangeSky(TexMan.CheckForTexture("SKY4",TexMan.Type_Any),TexMan.CheckForTexture("SKY4",TexMan.Type_Any));
			if ( skyEnable )
			{ TallSkyReplacements(); }
		}
		
		if ( mapName == "tn_map32" )
		Level.ChangeSky(TexMan.CheckForTexture("TSKYS",TexMan.Type_Any),TexMan.CheckForTexture("TSKYS",TexMan.Type_Any));
		
		if ( mapPrefix == "e4m" || mapName == "psx02b" )
		{
			Level.ReplaceTextures("FIRELAVA", "BFALL1", 0);
			Level.ReplaceTextures("FIRELAV2", "BFALL2", 0);
			Level.ReplaceTextures("FIRELAV3", "BFALL3", 0);
		}
		
		if ( mapname == "e3m7" || mapname == "cs_e3m7" || mapname == "ch_e3m7" || mapname == "co_e3m7" )
			Level.ReplaceTextures("CEIL4_2", "F_SKY1", 0);
		
		if (mapName == "tn_map26")
			Level.ReplaceTextures("RROCK04", "RROCK05", 0);
		
		/*
		if ( mapName == "map31" )
		Level.ReplaceTextures("MIDGRATE", "ZZWOLF15A", 0);
		
		if ( mapName == "map32" )
		Level.ReplaceTextures("MIDGRATE", "ZZWOLF15A", 0);
		*/
		
		//TNT Textures
		TNTTextureEnchancments();
		KICKEDTextures();
	}
	
	Void KICKEDTextures()
	{
		String mapName = level.MapName.MakeLower();
		if ( mapName.left(2) == "ka" )
		{
			Level.ReplaceTextures("BRONZE1", "KABRON1", 0);
			Level.ReplaceTextures("BROWN1", "KABWN1", 0);
			Level.ReplaceTextures("CRATE1", "KABOX1", 0);
			Level.ReplaceTextures("CRATE2", "KABOX2", 0);
			Level.ReplaceTextures("CRATE3", "KABOX3", 0);
			Level.ReplaceTextures("CRATELIT", "KABOXLIT", 0);
			Level.ReplaceTextures("CRATWIDE", "KABXWIDE", 0);
			Level.ReplaceTextures("STARTAN2", "KSTRTAN2", 0);
			Level.ReplaceTextures("TEKGREN1", "KTEKGRN1", 0);
			Level.ReplaceTextures("TEKGREN2", "KTEKGRN2", 0);
			Level.ReplaceTextures("TEKGREN3", "KTEKGRN3", 0);
			Level.ReplaceTextures("TEKLITE", "KTEKLIT", 0);
			Level.ReplaceTextures("STARGR2", "KSTRGR2", 0);
			Level.ReplaceTextures("DOOR3", "KADR3", 0);
			Level.ReplaceTextures("METAL", "KAMTL", 0);
			Level.ReplaceTextures("METAL2", "KAMTL2", 0);
			
			Level.ReplaceTextures("SW1BRCOM", "SW1KABCP", 0);
			Level.ReplaceTextures("SW2BRCOM", "SW2KABCP", 0);
			Level.ReplaceTextures("SW1BRIK", "SW1KABK", 0);
			Level.ReplaceTextures("SW2BRIK", "SW2KABK", 0);
			Level.ReplaceTextures("SW1BRCOM", "SW1KABCP", 0);
			Level.ReplaceTextures("SW2BRCOM", "SW2KABCP", 0);
			Level.ReplaceTextures("SW1BRN1", "SW1KAB1", 0);
			Level.ReplaceTextures("SW2BRN1", "SW2KAB1", 0);
			Level.ReplaceTextures("SW1MET2", "SW1KAM2", 0);
			Level.ReplaceTextures("SW2MET2", "SW2KAM2", 0);
			Level.ReplaceTextures("SW1TEK", "SW1KTK", 0);
			Level.ReplaceTextures("SW2TEK", "SW2KTK", 0);
			
			Level.ReplaceTextures("SW1COMM", "SW1KASV", 0);
			Level.ReplaceTextures("SW2COMM", "SW2KASV", 0);
		}
	}
	
	void TNTTextureEnchancments()
	{
		String mapPrefix = level.MapName.Left(3);
        mapPrefix = mapPrefix.MakeLower();
		String mapName = level.MapName.MakeLower();
		
		if ( mapPrefix == "tn_" || mapPrefix == "fd_" || mapName.left(6) == "fd_dmm")
		{
			if ( mapPrefix == "tn_" )
			{
				Level.ReplaceTextures("BIGDOOR1", "DRTN2_1",0);
			}
			
			Level.ReplaceTextures("DOBWIRE", 	"EHBWIRE", 0);
			Level.ReplaceTextures("DOBWIRE2", 	"EHBWIRE2", 0);
			Level.ReplaceTextures("TYIRONLG", "TYIRONLG2", 0);
			Level.ReplaceTextures("TYIRONSM", "TYIRONSM2", 0);
			Level.ReplaceTextures("DOGRMSC", 	"DOGRMC2", 0);
			Level.ReplaceTextures("DOGRID", 	 "DOGRI2", 0);
			Level.ReplaceTextures("DORED", 		 "DORED2", 0);
			Level.ReplaceTextures("DOPUNK4",	 "DOPNK42",0);
			Level.ReplaceTextures("DOGLDIR", 	 "DOGLDI2",0);
			Level.ReplaceTextures("PNK4EXIT",	"PK4EXIT2",0);
			Level.ReplaceTextures("TYWHEEL1", 	"TYWHEEL2",0);
			Level.ReplaceTextures("DOWINDOW", 	"DOWINDW2",0);
			Level.ReplaceTextures("LITEGRN1", 	"LITEGRN2",0);
			Level.ReplaceTextures("LITERED1", 	"LITERED2",0);
			Level.ReplaceTextures("DOGLPANL", 	"DOGLPAN2",0);
			Level.ReplaceTextures("MURAL1", 	 "MURAL1B",0);
			Level.ReplaceTextures("MURAL2", 	 "MURAL2B",0);
			Level.ReplaceTextures("STWALL", 	  "STWAL2",0);
			Level.ReplaceTextures("BIGMURAL", 	"BIGMURL2",0);
			Level.ReplaceTextures("LONGWALL", 	"LONGWAL2",0);
			Level.ReplaceTextures("SKIRTING", 	"SKIRTIN2",0);
			Level.ReplaceTextures("BIGWALL", 	 "BIGWAL2",0);
			Level.ReplaceTextures("DRTOPFR", 	 "DRTOPF2",0);
			Level.ReplaceTextures("DRFRONT", 	 "DRFRNT2",0);
			Level.ReplaceTextures("DRSIDE1", 	 "DRSID1B",0);
			Level.ReplaceTextures("DRSIDE2", 	 "DRSID2B",0);
			Level.ReplaceTextures("DRTOPSID", 	"DRTOPSIB",0);
			Level.ReplaceTextures("PILLAR", 	 "PILLAR2",0);
			Level.ReplaceTextures("WEBL", 	 	   "WEBL2",0);
		}
		
		if ( mapName == "tn_map31")
		{
			Level.ReplaceTextures("BIGBRIK1", "STWAL3",0);
			Level.ReplaceTextures("RROCK14","STWALF",0);
		}
	}
	
	void DCXskyreplacement()
	{
		String SkyName = TexMan.GetName(level.skytexture1);
		int flags = TexMan.ReturnFirst;
		String mapPrefix = level.MapName.Left(3);
		String mapName = level.MapName.MakeLower();
		mapPrefix = mapPrefix.MakeLower();
		
		if( SkyName == "SKY3TALS" )
		Level.ChangeSky(TexMan.CheckForTexture("SKYX4A",TexMan.Type_Any),TexMan.CheckForTexture("SKYX4A",TexMan.Type_Any));
		if( SkyName == "SKY3ATAS" )
		Level.ChangeSky(TexMan.CheckForTexture("SKYX5A",TexMan.Type_Any),TexMan.CheckForTexture("SKYX5A",TexMan.Type_Any));
		
		if ( MapPrefix == "e3m" || mapName.Left(5) == "psx02" || MapName == "ja_map17" || mapName == "e2m8" )
		{
			Level.ChangeSky(TexMan.CheckForTexture("SKYX4A",TexMan.Type_Any),TexMan.CheckForTexture("SKYX4A",TexMan.Type_Any));
		}
			
		if ( (mapName == "tn_map25") || (mapName == "tn_map26") || (mapName == "tn_map27") || (mapName == "tn_map28") )
		Level.ChangeSky(TexMan.CheckForTexture("SKYX4A",TexMan.Type_Any),TexMan.CheckForTexture("SKYX4A",TexMan.Type_Any));
		
		if ( (mapName == "ml_map10") || (mapName == "ml_map43") )
		Level.ChangeSky(TexMan.CheckForTexture("SKYX4A",TexMan.Type_Any),TexMan.CheckForTexture("SKYX4A",TexMan.Type_Any));	
	}
	
	void Wolfenstein3DTextures()
	{
		if ( Cvar.getcvar("W3D_Text_toggle").getint() == 1 )
		{
			Level.ReplaceTextures("ZZWOLF2", "UNIWOLF1", 0);
			Level.ReplaceTextures("ZZWOLF3", "UNIWOLF2", 0);
			Level.ReplaceTextures("ZZWOLF4", "UNIWOLF3", 0);
			Level.ReplaceTextures("ZZWOLF6", "UNIWOLF4", 0);
			Level.ReplaceTextures("ZZWOLF7", "UNIWOLF5", 0);
			Level.ReplaceTextures("ZZWOLF13", "UNIWOLF6", 0);			
		}		
		else if ( Cvar.getcvar("W3D_Text_toggle").getint() == 2 )
		{
			Level.ReplaceTextures("ZZWOLF2", "GBAWOLF1", 0);
			Level.ReplaceTextures("ZZWOLF3", "GBAWOLF2", 0);
			Level.ReplaceTextures("ZZWOLF4", "GBAWOLF3", 0);
			Level.ReplaceTextures("ZZWOLF6", "GBAWOLF4", 0);
			Level.ReplaceTextures("ZZWOLF7", "GBAWOLF5", 0);
			Level.ReplaceTextures("ZZWOLF13", "GBAWOLF6", 0);			
		}		
		else if ( Cvar.getcvar("W3D_Text_toggle").getint() == 3 )
		{
			Level.ReplaceTextures("ZZWOLF2",   "ZZWOLF1", 0);
			Level.ReplaceTextures("ZZWOLF3",   "ZZWOLF1", 0);
			Level.ReplaceTextures("ZZWOLF4",   "ZZWOLF1", 0);
			Level.ReplaceTextures("ZZWOLF6",   "ZZWOLF5", 0);
			Level.ReplaceTextures("ZZWOLF7",   "ZZWOLF5", 0);
			Level.ReplaceTextures("ZZWOLF12", "ZZWOLF11", 0);
			Level.ReplaceTextures("ZZWOLF13", "ZZWOLF11", 0);			
		}
	}
	
	void Doom64Doom2Replacements()
    {
		String mapPrefix = level.MapName.Left(3);
        mapPrefix = mapPrefix.MakeLower();
		String mapName = level.MapName.MakeLower();
		if ( mapPrefix == "ab_" )
        {
            Level.ReplaceTextures("BIGDOOR1", "ABIGDOR1", 0);
			Level.ReplaceTextures("CRACKLE2", "64CRACK2", 0);
			Level.ReplaceTextures("CRACKLE4", "64CRACK4", 0);
			Level.ReplaceTextures("SW1STONE", "SW1BRCOM", 0);
			Level.ReplaceTextures("SW2STONE", "SW2BRCOM", 0);
			Level.ReplaceTextures("DEM2_1", 	"DEM4_1", 0);
			Level.ReplaceTextures("DEM2_2", 	"DEM4_2", 0);
			Level.ReplaceTextures("DEM2_3", 	"DEM4_3", 0);
			Level.ReplaceTextures("DEM2_4",	    "DEM4_4", 0);
        }
	}
	
	//For the Jaguar Doom levels (Level Label "ja_")
	void JaguarDoomReplacements()
	{
		String mapName = level.MapName.MakeLower();
		if ( mapName.Left(3) == "ja_" )
		{
			Level.ReplaceTextures("FLAT14",   "FLOOR5_3", 0);
			Level.ReplaceTextures("SP_DUDE4",  "GSTONE3", 0);
			Level.ReplaceTextures("CEIL5_1",   "SLIME15", 0);
			Level.ReplaceTextures("FLOOR0_6",  "RROCK14", 0);
			Level.ReplaceTextures("FLOOR6_1", "FLOOR6_4", 0);
			Level.ReplaceTextures("FLOOR6_2",  "RROCK17", 0);
			Level.ReplaceTextures("SW1BRN1",  "SW1BRN1A", 0);
			Level.ReplaceTextures("SW2BRN1",  "SW2BRN1A", 0);
			Level.ReplaceTextures("FLAT4",     "RROCK19", 0);
			Level.ReplaceTextures("COMPSPAN", "COMPSPNJ", 0);
			Level.ReplaceTextures("COMPTALL", "COMPTALJ", 0);
			Level.ReplaceTextures("SP_HOT1",   "SP_HOTJ", 0);
			Level.ReplaceTextures("SW1GSTON", "SW1GSTON", 0);
			Level.ReplaceTextures("SW2GSTON", "SW2GSTON", 0);
			Level.ReplaceTextures("SW1HOT",    "SW1HOTJ", 0);
			Level.ReplaceTextures("SW2HOT",    "SW2HOTJ", 0);
			Level.ReplaceTextures("SW1WOOD",   "SW1METL", 0);
			Level.ReplaceTextures("SW2WOOD",   "SW2METL", 0);
			Level.ReplaceTextures("BIGDOOR6", "BIGDRJA6", 0);
			Level.ReplaceTextures("GSTSATYR", "GSATYRJA", 0);
		}
	}
	
	void PSX0BRepalcements()
	{
		String mapName = level.MapName.MakeLower();
		if ( (mapName == "psx02b") || (mapName == "psx03b") )
		{
			Level.ReplaceTextures("BRNPOIS",  "BRNPOIS1", TexMan.NOT_FLAT);
			Level.ReplaceTextures("NUKEPOIS", "NUKPOIS1", TexMan.NOT_FLAT);
			Level.ReplaceTextures("BIGDOOR7", "BIGDOR7A", TexMan.NOT_FLAT);
			Level.ReplaceTextures("SHAWN1",    "SHAWN1A", TexMan.NOT_FLAT);
			Level.ReplaceTextures("STEP1", 		"STEP1A", TexMan.NOT_FLAT);
			Level.ReplaceTextures("STEP2", 		"STEP2A", TexMan.NOT_FLAT);
			Level.ReplaceTextures("STEP3", 		"STEP3A", TexMan.NOT_FLAT);
			Level.ReplaceTextures("STEP5",      "STEP5A", TexMan.NOT_FLAT);
			Level.ReplaceTextures("SW1BRN1",  "SW1BRN1A", TexMan.NOT_FLAT);
			Level.ReplaceTextures("SW1STARG", "SW1STARA", TexMan.NOT_FLAT);
			Level.ReplaceTextures("SW1STONE", "SW1STONA", TexMan.NOT_FLAT);
			Level.ReplaceTextures("SW1STON2", "SW1STONB", TexMan.NOT_FLAT);
			Level.ReplaceTextures("SW2BRN1",  "SW2BRN1A", TexMan.NOT_FLAT);
			Level.ReplaceTextures("SW2STARG", "SW2STARA", TexMan.NOT_FLAT);
			Level.ReplaceTextures("SW2STONE", "SW2STONA", TexMan.NOT_FLAT);
			Level.ReplaceTextures("SW2STON2", "SW2STONB", TexMan.NOT_FLAT);
		}
	}
	
	void BasePSXMapTextures ()
	{
		String mapName = level.MapName.MakeLower();
		if ( mapName == "psx02" || mapName == "psx08" || MapName == "psx09" )
		{
			Level.ReplaceTextures("SW1BLUE", "SW1SKMTL", 0);
		}
	}
}