
class DCX_EventHandler : WadFusionHandler replaces WadFusionHandler
{

	///*
	TextureId TITLEPIC;
	TextureId VICTORY2;
	TextureId ENDPIC;
	TextureId E3TEXT;
	TextureId INTERPIC;
	TextureId DOOMTittle;
	TextureId UDOOMTittle;
	TextureId SIGILTittle;
	TextureId SIGIL2Tittle;
	TextureId DOOM2Tittle;
	TextureId CabalTitle;
	TextureId CabalEnd;
	
	override void OnRegister()
	{
		TITLEPIC = 	   	TexMan.CheckForTexture("TITLEPIC");
		INTERPIC = 		TexMan.CheckForTexture("INTERPIC");
		VICTORY2 =		TexMan.CheckForTexture("VICTORY2");
		ENDPIC = 	   	TexMan.CheckForTexture("INTER_E4");
		E3TEXT = 		TexMan.CheckForTexture("E3ENDINT");
		DOOMTittle =   	TexMan.CheckForTexture("TITLED1"); // why the double t AAAAAAAAAAA //yes =)
		UDOOMTittle =  	TexMan.CheckForTexture("ULDtitle");
		DOOM2Tittle =  	TexMan.CheckForTexture("DM2title");
		CabalTitle =  	TexMan.CheckForTexture("CSTITLE");
		CabalEnd =  	TexMan.CheckForTexture("CRBOSSBK");
	}
	
	override void RenderOverlay (RenderEvent e)
	{
		let rejects = CVar.FindCVar("wf_map_mlr").GetBool();
		int resX = Screen.GetWidth();
		int resY = Screen.GetHeight();
		
		// draw an overlay of the titlepic when changing replaced levels
		
		if ( CVar.FindCVar("wf_compat_nextmap").GetBool() )
		{
			string mapName = Level.MapName.MakeLower();
			if ( mapName == "wf_d1e4_ending" )
			{
					Level.SetFrozen(true);
			}
			if ( mapName == "masterhub" && !rejects )
			{
					Screen.DrawTexture(INTERPIC, false, 0, 0, DTA_FullScreen, 1);
					Level.SetFrozen(true);
			}
			if ( mapName == "e3m1" && CVar.GetCvar("dcx_playstationmaps").getint() > 0 )
			{
					Screen.DrawTexture(E3TEXT, false, 0, 0, DTA_FullScreen, 1);
					Level.SetFrozen(true);
			}
			if ( mapName == "cabalend" )
			{
					Screen.DrawTexture(CabalEnd, false, 0, 0, DTA_FullScreen, 1);
					Level.SetFrozen(true);
			}			
			if ( mapName == "inter_mlcs" )
			{
					Screen.DrawTexture(CabalTitle, false, 0, 0, DTA_FullScreen, 1);
					Level.SetFrozen(true);
			}
		}
	}
	//*/
	
	override void CheckReplacement(ReplaceEvent e)
	{
		string mapPrefix = Level.MapName.Left(3).MakeLower();
        mapPrefix = mapPrefix.MakeLower();
		String mapName = level.MapName.MakeLower();
		
		// increase the spiderdemon's health from 3000 to 9000 in Sigil 2
		int sigil2SpiderBoss = CVar.FindCVar("wf_compat_sigil2spiderboss").GetInt();
		if ( ( sigil2SpiderBoss == 1 && mapPrefix == "e6m" ) || sigil2SpiderBoss >= 2 )
			DoSigil2SpiderBossBuff(e);
		
		// replace plasmarifle and bfg9000 with incinerator and calamity blade, respectively
		int id24WeapSwap = CVar.FindCVar("wf_compat_id24_weapons").GetInt();
		if ( ( id24WeapSwap == 1 && mapPrefix == "lr_" ) || id24WeapSwap >= 2 )
			DoId24WeaponReplacements(e);
		
		
		if ( Cvar.getcvar("W3D_Text_toggle").getint() == 3 )
		{
			if (e.Replacee == 'Wolfensteinss')
			e.Replacement = 'Zombieman';
		}

	    If ( CVar.FindCVar("dcx_CustomMonsters").GetBool() &&  Cvar.findcvar("DCX_JAGBonuses").getint() == 2)
		{
			if (e.Replacee == 'HealthBonus')
			e.Replacement = 'DCX_JAGHealthbonus';
			
			if (e.Replacee == 'ArmorBonus')
			e.Replacement = 'DCX_JAGArmorbonus';
		}

		else If ( Cvar.findcvar("DCX_JAGBonuses").getint() == 1 )
		{
			if (e.Replacee == 'DCX_JAGHealthbonus')
			e.Replacement = 'Healthbonus';
			
			if (e.Replacee == 'DCX_JAGArmorbonus')
			e.Replacement = 'Armorbonus';
		}

		If ((Cvar.findcvar("Health_Cross_Toggle").getint() == 1))
		{
			if (e.Replacee == 'Stimpack')
			e.Replacement = 'Stimpack_BFG';
			
			if (e.Replacee == 'Medikit')
			e.Replacement = 'Medikit_BFG';
			
			if (e.Replacee == 'Berserk')
			e.Replacement = 'Berserk_BFG';
		}		
		else If((Cvar.findcvar("Health_Cross_Toggle").getint() == 2))
		{
			if (e.Replacee == 'Stimpack')
			e.Replacement = 'Stimpack_unity';
			
			if (e.Replacee == 'Medikit')
			e.Replacement = 'Medikit_unity';
			
			if (e.Replacee == 'Berserk')
			e.Replacement = 'Berserk_unity';
		}
		else If((Cvar.findcvar("Health_Cross_Toggle").getint() == 3))
		{
			if (e.Replacee == 'Stimpack')
			e.Replacement = 'Stimpack_eternal';
			
			if (e.Replacee == 'Medikit')
			e.Replacement = 'Medikit_eternal';
			
			if (e.Replacee == 'Berserk')
			e.Replacement = 'Berserk_eternal';
		}
		else If((Cvar.findcvar("Health_Cross_Toggle").getint() == 4))
		{
			if (e.Replacee == 'Stimpack')
			e.Replacement = 'Stimpack_rpg';
			
			if (e.Replacee == 'Medikit')
			e.Replacement = 'Medikit_rpg';
			
			if (e.Replacee == 'Berserk')
			e.Replacement = 'Berserk_rpg';
		}
		
		if ( mapName == "ka_map")
		{
			if ( CVar.FindCVar("dcx_CustomMonsters").GetBool() )
			{
			
			if (e.Replacee == 'Stimpack')
				e.Replacement = 'Stimpack_kick';
			
			if (e.Replacee == 'Medikit')
				e.Replacement = 'Medikit_kick';
				
			if (e.Replacee == 'Clip')
				e.Replacement = 'Clip_kick';
			
			if (e.Replacee == 'ClipBox')
				e.Replacement = 'ClipBox_kick';
				
			if (e.Replacee == 'Shell')
				e.Replacement = 'Shell_kick';
			
			if (e.Replacee == 'Shellbox')
				e.Replacement = 'ShellBox_kick';
				
			if (e.Replacee == 'RocketAmmo')
				e.Replacement = 'RocketAmmo_kick';
			
			if (e.Replacee == 'RocketBox')
				e.Replacement = 'RocketBox_kick';
				
			if (e.Replacee == 'Cell')
				e.Replacement = 'Cell_kick';
				
			if (e.Replacee == 'CellPack')
				e.Replacement = 'CellPack_kick';
				
			if (e.Replacee == 'BlueCard')
				e.Replacement = 'BlueCard_Kick';
				
			if (e.Replacee == 'YellowCard')
				e.Replacement = 'YellowCard_kick';
				
			if (e.Replacee == 'RedCard')
				e.Replacement = 'RedCard_Kick';
				
			//KickSodaCan
			if (e.Replacee == 'HealthBonus')
				e.Replacement = 'KickSodaCan';
			
			//KickArmorBonus
			if (e.Replacee == 'ArmorBonus')
				e.Replacement = 'KickArmorBonus';
			
			//SoulSphere_Kick
			if (e.Replacee == 'SoulSphere')
				e.Replacement = 'SoulSphere_Kick';

			//Doomimp
			if (e.Replacee == 'Doomimp')
			{
				e.Replacement = 'Dcx_SurferMutant1';
			}
			//Shotgunguy
			if (e.Replacee == 'Shotgunguy')
			{
				e.Replacement = 'Dcx_SurferMutant2';
			}
			//Demon
			if (e.Replacee == 'Demon')
			{
				e.Replacement = 'Dcx_LoungeSinger';
			}
			//LostSoul
			if (e.Replacee == 'LostSoul')
			{
				e.Replacement = 'Dcx_BottleOfSpew';
			}
			//SpiderMastermind
			if (e.Replacee == 'SpiderMastermind')
			{
				e.Replacement = 'Dcx_GiantCanOfSpew';
			}
			//Column
			if (e.Replacee == 'Column')
			{
				e.Replacement = 'Dcx_Kick_Column';
			}
			//TechLamp
			if (e.Replacee == 'TechLamp')
			{
				e.Replacement = 'Dcx_Kick_TechLamp';
			}
			//TechPillar
			if (e.Replacee == 'TechPillar')
			{
				e.Replacement = 'Dcx_Kick_TechPillar';
			}
			
			}
		}

		if ( mapName == "map31" || mapName == "map32")
		{
			if ( CVar.findcvar("otg_wolfrifle").getint() == 1 && CVar.GetCVar("dcx_CustomMonsters").GetBool() )			{
			//Machine Gun Woohooo!
			if (e.Replacee == 'Chaingun')
			{
				e.Replacement = 'Keyboard_Machinegun';
			}
			
			}
		}

		if ( mapPrefix == "ja_" && Cvar.findcvar("DCX_JAGBonuses").getint() == 0 && CVar.FindCVar("dcx_CustomMonsters").GetBool() )
		{
			if (e.Replacee == 'HealthBonus')
			e.Replacement = 'DCX_JAGHealthbonus';
			
			if (e.Replacee == 'ArmorBonus')
			e.Replacement = 'DCX_JAGArmorbonus';	
			}
		
		if ( mapPrefix == "ab_" )
		{
			if ( mapName == "ab_map33" )
			{
				if (e.Replacee == 'Zombieman')
				e.Replacement = 'DCX_MarineBotSpawner';		
			}
			
			if ( CVar.GetCVar("dcx_D64D2Xtras").GetBool() && CVar.GetCVar("dcx_CustomMonsters").GetBool() )
			{
				if (e.Replacee == 'Chainsaw')
				e.Replacement = 'DCX_DoubleBladedChainsaw';
			
				if (e.Replacee == 'Plasmarifle')
				e.Replacement = 'DCX_PlasmaRifleMKII';
				
				if (e.Replacee == 'Arachnotron')
				e.Replacement = 'DCX_Dualarachnotron';
			
				if (e.Replacee == 'Painelemental')
				e.Replacement = 'DCX_DualPainelemental';
			
				if (e.Replacee == 'LostSoul')
				e.Replacement = 'DCX_ForgottenSoul';
				
				if (e.Replacee == 'Revenant')
				e.Replacement = 'DCX_DarkRevenant';
			}
			
			if (e.Replacee == 'Meat4')
			e.Replacement = 'Dcx_ChooserDemon';
			
			if (e.Replacee == 'Meat3')
			e.Replacement = 'Dcx_VoodooExploder';
			
			if (e.Replacee == 'BossEye')
			e.Replacement = 'Dcx_D64D2BossEye';
			
			if (e.Replacee == 'HangBNoBrain')
			e.Replacement = 'Dcx_HangBNoBrainNS';
			
			if (e.Replacee == 'HangNoGuts')
			e.Replacement = 'Dcx_HangNoGutsNS';
			
			if (e.Replacee == 'HangTLookingDown')
			e.Replacement = 'Dcx_HangTLookingDownNS';
			
			if (e.Replacee == 'HangTNoBrain')
			e.Replacement = 'Dcx_HangTNoBrainNS';
			
			if (e.Replacee == 'HangTSkull')
			e.Replacement = 'Dcx_HangTSkullNS';
			
			if (e.Replacee == 'BurningBarrel')
			e.Replacement = 'Dcx_Flames';
			
			if ( CVar.GetCVar("dcx_CustomMonsters").GetBool() )
			{			
				if (e.Replacee == 'CommanderKeen')
				e.Replacement = 'DCX_NightmareImp';
			
				if (e.Replacee == 'GibbedMarineExtra')
				e.Replacement = 'DCX_NightmareCacodemon';
				
				if ( mapName == "ab_map30" )
				{
					if (e.Replacee == 'Spidermastermind')
					e.Replacement = 'DCX_Motherdemon';
				}
			}
			else
			{
				if (e.Replacee == 'CommanderKeen')
				e.Replacement = 'Doomimp';
			
				if (e.Replacee == 'GibbedMarineExtra')
				e.Replacement = 'Cacodemon';
			}
		}
		
		if ( mapPrefix == "lr_" )
		{
			//Replace the legacy of rust monsters with doom 2 equivilants for certain gameplay mods.
			
			if ( !CVar.GetCVar("dcx_CustomMonsters").GetBool() )
			{
				if (e.Replacee == 'ID24Ghoul') //Ghoul
				e.Replacement = 'Lostsoul';
				
				if (e.Replacee == 'ID24Banshee') //Banshee
				e.Replacement = 'Lostsoul';
				
				if (e.Replacee == 'ID24Mindweaver') //Mindweaver
				e.Replacement = 'Arachnotron';
				
				if (e.Replacee == 'ID24PlasmaGuy') //ShockTropper
				e.Replacement = 'Revenant';
				
				if (e.Replacee == 'ID24Vassago') //Vassago
				{
					if ( mapName == "lr_map13" || mapName == "lr_map14" )
					{ e.Replacement = 'Hellknight'; }
					else
					{ e.Replacement = 'Baronofhell'; }
				}
				
				if (e.Replacee == 'ID24Tyrant' || e.Replacee == 'ID24TyrantBoss2') //Tyrant
				e.Replacement = 'Baronofhell';
				
				if (e.Replacee == 'ID24TyrantBoss1')
				e.Replacement = 'Cyberdemon';
			}
		}
	}
	
	//Make sure the map specific flags still work
	override void CheckReplacee (ReplacedEvent e)
	{		
		String mapName = level.MapName.MakeLower();
		
		if (e.Replacement == 'DCX_DualArachnotron')
		e.Replacee = 'Arachnotron';
		
		if (e.Replacement == 'DCX_DualArachnotron')
		e.Replacee = 'Arachnotron';
		
		if (e.Replacement == 'DCX_DualCyberdemon')
		e.Replacee = 'Cyberdemon';
		
		if (e.Replacement == 'DCX_Motherdemon')
		e.Replacee = 'Spidermastermind';
	}
	
	override void WorldLoaded (WorldEvent e)
	{
		int texSwapAll = CVar.FindCVar("wf_compat_texswap_all").GetInt();
		int  renderMode  = CVar.FindCVar("vid_rendermode").GetInt();
		bool skyEnable   = CVar.FindCVar("uw_sky_enable").GetBool();
		
		// wf_tex_swap.zs
		// replace conflicting textures based on which map is loaded
		if ( CVar.FindCVar("wf_compat_texswap_d1").GetBool() && texSwapAll <= 0 )
			DoDoom1TextureReplacements();
		if ( CVar.FindCVar("wf_compat_texswap_fd").GetBool() && texSwapAll <= 0 )
			DoFinalDoomTextureReplacements();
		if ( CVar.FindCVar("wf_compat_texswap_id1").GetBool() && texSwapAll <= 0 )
			DoId1TextureReplacements();
		if ( CVar.FindCVar("wf_compat_texswap_ml").GetBool() && texSwapAll <= 0 )
			DoMasterLevelsTextureReplacements();
		
		// temporary fix for the exit sector sky in the kex version of map20
		// should be removed when gzdoom adds support for skydefs
		if ( CVar.FindCVar("wf_compat_mapfixes").GetBool() )
		{
			string mapName = Level.MapName.MakeLower();
			if ( mapName == "map20" )
				Level.ReplaceTextures("F_RSKY3", "F_SKY1", TexMan.NOT_WALL);
		}
		// wf_tex_swap_all.zs
		// force texture replacement on all levels
		// this feature mostly exists for compatibility with doom 1 and final doom mods
		// these disable the regular texture replacements
		// each texture replacement can be toggled individually, in case a mod needs to replace some of them
		switch ( texSwapAll )
		{
			case 1:  DoTextureReplacementsAllDoom1();      break;
			case 2:  DoTextureReplacementsAllTnt();        break;
			case 3:  DoTextureReplacementsAllPlutonia();   break;
			case 4:  DoTextureReplacementsAllId1();        break;
			case 5:  DoTextureReplacementsAllMlKlie();     break;
			case 6:  DoTextureReplacementsAllMlAnderson(); break;
			case 7:  DoTextureReplacementsAllMlFlynn();    break;
			case 8:  DoTextureReplacementsAllMlrMines();   break;
			case 9:  DoTextureReplacementsAllMlrAnomaly(); break;
			case 10: DoTextureReplacementsAllMlrFarside(); break;
			case 11: DoTextureReplacementsAllMlrTrouble(); break;
			case 12: DoTextureReplacementsAllMlrUdtwid();  break;
		}
		
		if ( CVar.FindCVar("wf_compat_changemusic").GetBool() )
		{
			// wf_music_sigil.zs
			// Sigil's map music should be left undefined in MAPINFO,
			// that way the music playback gets initiated by the script,
			// without potentially playing the wrong music for one tick
			PlaySigilMusic();
		}
		
		if ( skyEnable )
		{ TallSkyReplacements(); }
		if ( CVar.FindCVar("dcx_TextureEchancements").GetBool() )
		{ TextureEnchancements(); }
		if ( CVar.FindCVar("fs_toggle").GetBool() ) 
		{ DCXskyreplacement(); }
		
		//CabalLevelOrder(); 
		
		Doom64Doom2Replacements();
		JaguarDoomReplacements();
		PSX0BRepalcements();		
		Wolfenstein3DTextures();
		BlankMapTransitions();
		BasePSXMapTextures();
		
	}
	
	override void WorldTick()
	{
		if ( CVar.FindCVar("wf_compat_nextmap").GetBool() )
		{
			LevelReplacement();
			
			// replace e1m8 or e1m4 with the maps that Romero authored
			// as a warm-up exercise for the cancelled game Blackroom
			DoBlackroomMapReplacements();
			
			// wf_masterlevels.zs
			// add the reject levels to the master levels mapset
			DCX_AddMasterLevelsRejects();
		}
	}
	
	override void WorldThingSpawned(worldEvent e)
	{	
		// override gzdoom's transparency render style for id24 actors
		if ( CVar.FindCVar("wf_id24trans").GetBool() )
			DoId24ActorTransparency(e);
		
		// don't count spawned enemies e.g. icon of sin summons
		if ( CVar.FindCVar("wf_compat_killcountfix").GetBool() )
		{
			if ( Level.MapTime > 0 )
				RevertKillCounter(e);
		}
		
		let w = Wolfensteinss(e.thing);
		if (w)
		{
			if ( Cvar.getcvar("W3D_Text_toggle").getint() >= 1 )
			w.SeeSound = "wolfss/sight2";
		}
		
		//super.WorldThingSpawned();
	}
	
	void BlankMapTransitions()
	{
		string mapName = Level.MapName.MakeLower();
		if ( mapName.left(6) == "wf_newgame_" )
		{
				Level.StartSlideShow("BlankMapTransitions");
		}
	}
	
	void LevelReplacement()
	{
		//All these here toggle weather or not you play the console maps in the base campain.
		
		let rejects = CVar.FindCVar("wf_map_mlr").GetBool();
		String mapName = level.MapName.MakeLower();
		
		if ( mapName == "masterhub" && !rejects )
		{
			Level.ChangeLevel("ml_map01",0,CHANGELEVEL_NOINTERMISSION|CHANGELEVEL_RESETHEALTH|CHANGELEVEL_RESETINVENTORY,-1);
		}
		
		if ( mapName == "e2m7" ) // Adds alter of extraction as a secret map
		{
			if ( CVar.GetCvar("dcx_playstationmaps").getint() == 2 )
				level.NextSecretMap = "PSX01B";
			else if ( CVar.GetCvar("dcx_playstationmaps").getint() == 1 )
				level.NextSecretMap =  "PSX01";
		}
		
		if ( mapName == "e3m1" ) // Thanks domyoji81!
        {
          if (CVar.GetCvar("dcx_playstationmaps").getint() == 2 )
               Level.ChangeLevel("psx02b",0,CHANGELEVEL_NOINTERMISSION|CHANGELEVEL_RESETHEALTH|CHANGELEVEL_RESETINVENTORY,-1);
		  if (CVar.GetCvar("dcx_playstationmaps").getint() == 1 )
               Level.ChangeLevel("psx02",0,CHANGELEVEL_NOINTERMISSION|CHANGELEVEL_RESETHEALTH|CHANGELEVEL_RESETINVENTORY,-1);
        } 
		if ( mapName == "e3m6" )
		{
			if ( CVar.GetCvar("dcx_playstationmaps").getint() == 2 )
				level.NextSecretMap = "PSX03B";
			else if ( CVar.GetCvar("dcx_playstationmaps").getint() == 1 )
				level.NextSecretMap =  "PSX03";
			else
				level.NextSecretMap = "e3m9";
		}
		
		if ( mapName == "e4m8" )
		{
			if ( CVar.GetCvar("dcx_playstationmaps").getint() >= 1 )
				level.NextMap = "PSX04";
		}
		if ( mapName == "map29" )
		{
			if ( CVar.GetCvar("dcx_playstationmaps").getint() >= 1 )
				level.NextMap = "psx07";
			else
				level.NextMap = "map30";
		}
	}
}

class DCX_PerMapReplacementHandler : EventHandler
{
	
}

class DCX_BloodHandler : EventHandler
{
	override void WorldThingSpawned(WorldEvent e)
	{
		if (!e.Thing) return;
		Actor mo = e.Thing;
		if (!mo.bShootable) return;
		CBlood.Process(mo);
	}
}

class DCX_MusicHandler : StaticEventHandler
{
	override void PostUiTick()
	{
		// get map name and currently playing music
		string mapName = level.MapName.MakeLower();
		string music = MusPlaying.Name.MakeLower();
		if ( Cvar.getcvar("W3D_Text_toggle").getint() == 3 )
		{
			if ( (CVar.FindCVar("wf_mus_idkfa").GetBool() ) )
			{
				if ( music == "h_ultima" )
				music = "h_doom";
			
				if ( music == "h_evil" )
				music = "h_doom";
				
				S_ChangeMusic(music);
			}
			else
			{
				if ( music == "d_ultima" )
				music = "d_doom";
			
				if ( music == "d_evil" )
				music = "d_doom";
				
				S_ChangeMusic(music);
			}
		}
		else
		{
			if ( (CVar.FindCVar("wf_mus_idkfa").GetBool() ) )
			{
				if ( mapName == "map31")
				{
					if ( music == "h_doom" )
					music = "h_evil";
				}
			
				if ( mapName == "map32")
				{
					if ( music == "h_doom" )
					music = "h_ultima";
				}
				
				S_ChangeMusic(music);
			}
			else
			{
				if ( mapName == "map31")
				{
					if ( music == "d_doom" )
					music = "d_evil";
				}
			
				if ( mapName == "map32")
				{
					if ( music == "d_doom" )
					music = "d_ultima";
				}
				
				S_ChangeMusic(music);
			}			
		}
		
		
				
		if ( (CVar.FindCVar("dcx_3DO_Music").GetBool() ) && (CVar.FindCVar("wf_mus_idkfa").GetBool() != true) && ( mapName.left(3) != "ja_" ) )
		{
			if ( music == "d_e1m1" || music == "d_e2m4" || music == "d_inter")
				music = "o_e1m1";
			
			if ( music == "d_e1m2" || music == "d_e2m5")
				music = "o_e1m2";
			
			if ( music == "d_e1m3" || music == "d_e2m6")
			{
				if ( mapName == "psx01" )
					music = "o_e1m5";
				else
					music = "o_e1m3";
			}
			
			if ( music == "d_e1m4" || music == "d_e2m7")
				music = "o_e1m4";
			
			if ( music == "d_e1m5" || music == "d_e2m8")
				music = "o_e1m5";
			
			if ( music == "d_e1m6" || music == "d_e2m3" || music == "d_e3m7")
				music = "o_e1m6";
			
			if ( music == "d_e1m7" || music == "d_e3m3" || music == "d_victor")
				music = "o_e1m7";
			
			if ( music == "d_e1m8" || music == "d_e2m9" || music == "d_e3m8")
				music = "o_e1m8";
			
			if ( music == "d_e1m9" || music == "d_e3m9" )
				music = "o_e1m9";
			
			if ( music == "d_e2m1" || music == "d_e3m4" )
				music = "o_e2m1";
			
			if ( music == "d_e3m1" || music == "d_e3m6")
				music = "o_e2m9";
			
			if ( music == "d_e3m2" || music == "d_e2m2" || music == "d_e3m5")
			{
				if ( mapName == "psx02" )
					music = "o_e1m9";
				else
					music = "o_e3m2";
			}
			
			if ( music == "d_intro" || music == "d_introa" )
				music = "o_intro";
			
			if ( music == "d_bunny" )
				music = "o_bunny";
				
			S_ChangeMusic(music);
		}
		else
		{
		
		if ( mapName.left(3) != "ja_" )
		{
			if ( music == "o_e1m1" )
			{
				if ( mapName == "e1m1" )
					music = "d_e1m1";
				else if ( mapName == "e2m4" )
					music = "d_e2m4";
				else
					music == "d_inter";
			}
			
			if ( music == "o_e1m2" )
			{
				if ( mapName == "e2m5" )
					music = "d_e2m5";
				else
					music = "d_e1m2";
			}
			
			if ( music == "o_e1m3" )
			{
				if ( mapName == "e2m6" )
					music == "d_e2m6";
				else
					music = "d_e1m3";
			}
			
			if ( music == "o_e1m4" )
			{
				if ( mapName == "e2m7" )
					music == "d_e2m7";
				else
					music = "d_e1m4";
			}
			
			if ( music == "o_e1m5" )
			{
				if ( mapName == "e2m8" )
					music == "d_e2m8";
				else if ( mapName == "psx01" )
					music = "d_e2m6";
				else
					music = "d_e1m5";
			}
			
			if ( music == "o_e1m6" )
			{
				if ( mapName == "e2m3" )
					music = "d_e2m3";
				else if ( mapName == "e3m7" )
					music = "d_e3m7";
				else
					music = "d_e1m6";
			}
			
			if ( music == "o_e1m7" )
			{
				if ( mapName == "e1m7" )
					music = "d_e1m7";
				else if ( mapName == "e3m3" )
					music = "d_e3m3";
				else
					music = "d_victor";
			}
			
			if ( music == "o_e1m8" )
			{
				if ( mapName == "e2m9" )
					music == "d_e2m9";
				else if ( mapName == "e3m8" )
					music = "d_e3m8";
				else
					music = "d_e1m8";
			}
			
			if ( music == "o_e1m9" )
			{
				if ( mapName == "e3m9" )
					music = "d_e3m9";
				else if ( mapName == "psx02" )
					music = "d_e2m2";
				else
					music = "d_e1m9";
			}
			
			if ( music == "o_e2m1" )
			{
				if ( mapName == "e3m4" )
					music == "d_e3m4";
				else
					music = "d_e2m1";
			}
			
			if ( music == "o_e2m9" )
			{
				if ( mapName == "e3m6" )
					music = "d_e3m6";
				else
					music = "d_e3m1";
			}
			
			if ( music == "o_e3m2" )
			{
				if ( mapName == "e2m2" )
					music = "d_e2m2";
				else if ( mapName == "e3m5" )
					music == "d_e3m5";
				else
					music = "d_e3m2";
			}
			
			if ( music == "o_intro" )
				music = "d_intro";
			
			if ( music == "o_bunny" )
				music = "d_bunny";
				
			S_ChangeMusic(music);
			}
			
			if ( mapName == "e3m1" && CVar.GetCvar("dcx_playstationmaps").getint() > 0 )
			{
				if ( music == "d_e3m1" )
					music = "d_psx02";
				
				S_ChangeMusic(music);
			}
		}
	}
}

class CBlood : Actor
{
	Default
	{
		+NOINTERACTION
	}

	static void Process(Actor mo)
	{
		String className = "CBlood" .. mo.GetClassName();
		class<Actor> cls = className;

		Actor blood = NULL;

		if (cls)
		{
			blood = Spawn(cls, mo.Pos, NO_REPLACE);
		}

		if (blood)
		{
			mo.bNoBlood = blood.bNoBlood;
			mo.CopyBloodColor(blood);
			blood.Destroy();
		}
	}
}

class CBloodBaronOfHell : CBlood
{
	Default
	{
		BloodColor "30 67 23";
	}
}

class CBloodHellKnight : CBloodBaronOfHell {}

class CBloodCacodemon : CBlood
{
	Default
	{
		BloodColor "00 00 F9";
	}
}

class CBloodLostSoul : CBlood
{
	Default
	{
		+NOBLOOD
	}
}