class DCX_StaticHandler : WadFusionStaticHandler Replaces WadFusionStaticHandler
{
	override void NetworkProcess(ConsoleEvent e)
	{
		if (e.Name ~== "NewGameChangeLevelInputEvent")
			DCX_NewGameChangeLevelInput(); // wf_newgame.zs
		
		if (e.Name ~== "IntermissionStoryEvent")
			Level.StartIntermission(intermission, FSTATE_INLEVELNOWIPE);
	}
	
	override void WorldTick()
	{
		if ( CVar.FindCVar("wf_compat_nextmap").GetBool() )
			FullRunStory(); // wf_fullrun.zs in wadfusion.pk3

		DCX_NewGameIntro();
		DCX_IntermissionStory();
		
		FullRunMultiplayerTakeStuff(); // wf_story.zs in wadfusion.pk3
	}
	
	override void RenderOverlay(RenderEvent e)
	{
		DCX_NewGameTitlePic();
		FullRunMultiplayer();
	}
	
	override void WorldUnloaded(WorldEvent e)
	{
		// force pistol start on half of the master levels.
		// this is needed to support switching between the xaser order,
		// in which they should have pistol starts,
		// and the rejects order, in which they shouldn't
		if ( CVar.FindCVar("wf_compat_pistolstart").GetBool() )
		{
			if ( !CVar.FindCVar("wf_map_mlr").GetBool() )
			{
				if ( Level.NextMap == "ml_map10" || Level.NextMap == "ml_map11" ||
					 Level.NextMap == "ml_map12" || Level.NextMap == "ml_map13" ||
					 Level.NextMap == "ml_map14" || Level.NextMap == "ml_map15" || 
					 Level.NextMap == "ml_map18" || Level.NextMap == "ml_map20" )
				{
					ForcePistolStart();
				}
			}
		}
		
		if ( CVar.FindCVar("wf_compat_nextmap").GetBool() )
			DCX_FullRun(); // wf_fullrun.zs
	}
	
	ui void DCX_NewGameTitlePic()
	{
		string mapName = Level.MapName.MakeLower();
		if ( mapName.Left(10) == "wf_newgame" || mapName.Left(8) == "wf_story" )
		{
			Level.SetFrozen(true);
			
			TextureId titlePic = TexMan.CheckForTexture("TITLEPIC");
			TextureId titleD1 = TexMan.CheckForTexture("TITLED1");
			TextureId titleUD = TexMan.CheckForTexture("TITLEUD");
			TextureId titleE4 = TexMan.CheckForTexture("TITLEE4");
			TextureId TitleEU = TexMan.CheckForTexture("final2");
			TextureId titleJA = TexMan.CheckForTexture("TITLEJA");
			TextureId titleS1 = TexMan.CheckForTexture("TITLES1");
			TextureId titleS2 = TexMan.CheckForTexture("TITLES2");
			TextureId titleD2 = TexMan.CheckForTexture("TITLED2");
			TextureId titleML = TexMan.CheckForTexture("TITLEML");
			TextureId titleCA = TexMan.CheckForTexture("TITLECA");
			TextureId titleIN = TexMan.CheckForTexture("TITLEIN");
			TextureId titleTI = TexMan.CheckForTexture("TITLETI");
			TextureId titleNV = TexMan.CheckForTexture("TITLENV");
			TextureId titleLR = TexMan.CheckForTexture("TITLELR");
			TextureId titleTN = TexMan.CheckForTexture("TITLETN");
			TextureId titlePL = TexMan.CheckForTexture("TITLEPL");
			TextureId titleAB = TexMan.CheckForTexture("TITLEAB");
			TextureId titleDZ = TexMan.CheckForTexture("TITLEDZ");
			TextureId titleTR = TexMan.CheckForTexture("TITLETR");
			TextureId titlePT = TexMan.CheckForTexture("TITLEPT");
			TextureId titleKA = TexMan.CheckForTexture("TITLEKA");
			TextureId titleLE = TexMan.CheckForTexture("TITLELE");
			TextureId titlePG = TexMan.CheckForTexture("TITLEPG");
			TextureId titleHP = TexMan.CheckForTexture("TITLEHP");
			
			// draw a black overlay over the entire screen
			// hides the HUD under the titlepic overlay that gets drawn next
			int resX = Screen.GetWidth();
			int resY = Screen.GetHeight();
			Screen.DrawTexture(titlePic, false, 0, 0, DTA_ScaleX, resX, DTA_ScaleY, resY, DTA_FillColor, 0);
			
			if ( mapName.Left(10) == "wf_newgame" )
			{
				if ( CVar.FindCVar("wf_compat_titlepics").GetBool() )
				{
					if ( nextMap == "e1m1" || nextMap == "e2m1" || nextMap == "e3m1" || nextMap == "psx02" || nextMap == "psx02b" )						Screen.DrawTexture(titleD1, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "e4m1" )
						Screen.DrawTexture(titleE4, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "e5m1" )
						Screen.DrawTexture(titleS1, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "e6m1" )
						Screen.DrawTexture(titleS2, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "eu_map01" )
						Screen.DrawTexture(titleEU, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "ja_map01" )
						Screen.DrawTexture(titleJA, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "map01" || nextMap == "map12" || nextMap == "map21")
						Screen.DrawTexture(titleD2, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "pg_map01" || nextMap == "pg_map12" || nextMap == "pg_map21")
						Screen.DrawTexture(titlePG, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "hp_map01" || nextMap == "hp_map12" || nextMap == "hp_map21")
						Screen.DrawTexture(titleHP, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "ml_map01" || nextMap == "masterhub" )
						Screen.DrawTexture(titleML, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "ml_map19" )
						Screen.DrawTexture(titleCA, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "ml_map33" )
						Screen.DrawTexture(titleIN, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "ml_map29" )
						Screen.DrawTexture(titleTI, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "nv_map01" )
						Screen.DrawTexture(titleNV, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "ka_map" )
						Screen.DrawTexture(titleKA, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "lr_map01" || nextMap == "lr_map08" )
						Screen.DrawTexture(titleLR, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "tn_map01" || nextMap == "tn_map12" || nextMap == "tn_map21" )
						Screen.DrawTexture(titleTN, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "le_e1m1" || nextMap == "le_e2m1" || nextMap == "le_e3m1" )
						Screen.DrawTexture(titleLE, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "pl_map01" || nextMap == "pl_map12" || nextMap == "pl_map21" )
						Screen.DrawTexture(titlePL, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "pt_map01" || nextMap == "pt_map12" || nextMap == "pt_map21" )
						Screen.DrawTexture(titlePT, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "dz_map01" || nextMap == "dz_map12" || nextMap == "dz_map21" )
						Screen.DrawTexture(titleDZ, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "tr_map01" || nextMap == "tr_map12" || nextMap == "tr_map21" )
						Screen.DrawTexture(titleTR, false, 0, 0, DTA_FullScreen, 1);
					else if ( nextMap == "ab_map01" || nextMap == "ab_map12" || nextMap == "ab_map21" )
						Screen.DrawTexture(titleAB, false, 0, 0, DTA_FullScreen, 1);
					else
						Screen.DrawTexture(titlePic, false, 0, 0, DTA_FullScreen, 1);
				}
				else
					Screen.DrawTexture(titlePic, false, 0, 0, DTA_FullScreen, 1);
			}
			else
				Screen.DrawTexture(titlePic, false, 0, 0, DTA_FullScreen, 1);
		}
	}
	
	void DCX_NewGameIntro()
	{
		string mapName = Level.MapName.MakeLower();
		if ( mapName.Left(10) == "wf_newgame" )
		{
			if ( Level.MapTime == 0 )
			{
				// starting an empty intermission on the first tic removes
				// the screen wipe that usually happens when changing levels
				
				if ( !fullRunNewGame )
					Level.StartIntermission("WadFusionNewGame", FSTATE_INLEVELNOWIPE);
					
				if ( mapName == "e3m1" && CVar.GetCvar("dcx_playstationmaps").getint() > 0  )
					Level.StartIntermission("WadFusionNewGame", FSTATE_INLEVELNOWIPE);
				
				if ( mapName != "wf_newgame")
					nextMap = mapName.Mid(11);
				
				if ( CVar.FindCVar("wf_compat_titlepics").GetBool() )
				{
					// play title music for each game
					if ( nextMap == "e1m1" || nextMap == "e2m1" || nextMap == "e3m1" )
						S_ChangeMusic("d_intro", 0, false);
					else if ( nextMap == "e4m1" )
						S_ChangeMusic("d_intr2", 0, false);
					else if ( nextMap == "e5m1" )
						PlaySigilIntroMusic();
					else if ( nextMap == "eu_map01" )
						S_ChangeMusic("D_BETA23", 0, false);
					else if ( nextMap == "ja_map01" )
						S_ChangeMusic("O_INTRO", 0, false);
					else if ( nextMap == "e6m1" )
						PlaySigil2IntroMusic();
					else if ( nextMap == "map01" || nextMap == "map12" || nextMap == "map21" )
						S_ChangeMusic("d_dm2ttl", 0, false);
					else if ( nextMap == "pg_map01" || nextMap == "pg_map12" || nextMap == "pg_map21")
						S_ChangeMusic("D_TITLEPER", 0, false);
					else if ( nextMap == "hp_map01" || nextMap == "hp_map12" || nextMap == "hp_map21")
						S_ChangeMusic("D_TITLEH2P", 0, false);						
					else if ( nextMap == "ml_map01" || nextMap == "masterhub" )
						S_ChangeMusic("D_TITLEM", 0, false);
					else if ( nextMap == "ml_map19" )
						S_ChangeMusic("D_TITLM2", 0, false);
					else if ( nextMap == "ml_map33" )
						S_ChangeMusic("D_CHIRON", 0, false);
					else if ( nextMap == "ml_map29" )
						S_ChangeMusic("D_ANOMALY", 0, false);
					else if ( nextMap == "nv_map01" )
						S_ChangeMusic("D_NRFTLT", 0, false);
					else if ( nextMap == "ka_map" )
						S_ChangeMusic("KA_INTRO", 0, false);
					else if ( nextMap == "lr_map01" || nextMap == "lr_map08" )
						S_ChangeMusic("x_dm2ttl", 0, false);
					else if ( nextMap == "tn_map01" || nextMap == "tn_map12" || nextMap == "tn_map21" )
						S_ChangeMusic("t_dm2ttl", 0, false);
					else if ( nextMap == "pl_map01" || nextMap == "pl_map12" || nextMap == "pl_map21" )
						S_ChangeMusic("p_dm2ttl", 0, false);
					else if ( nextMap == "dz_map01" || nextMap == "dz_map12" || nextMap == "dz_map21" )
						S_ChangeMusic("D_MINUS1", 0, false);
					else if ( nextMap == "pt_map01" || nextMap == "pt_map12" || nextMap == "pt_map21" )
						S_ChangeMusic("D_BETA01", 0, false);
					else if ( nextMap == "tr_map01" || nextMap == "tr_map12" || nextMap == "tr_map21" )
						S_ChangeMusic("d_titl_tr", 0, false);
					else if ( nextMap == "le_e1m1" || nextMap == "le_e2m1" || nextMap == "le_e3m1" )
						S_ChangeMusic("LE_INTRO", 0, false);
					else if ( nextMap == "ab_map01" || nextMap == "ab_map12" || nextMap == "ab_map21" )
						S_ChangeMusic("D_TITLEA", 0, false);
					else
						NewGameChangeLevel();
				}
				else
					NewGameChangeLevel();
			}
		}
	}
	
	void DCX_NewGameChangeLevelInput() // Does nothing lmao!
	{
		let rejects = CVar.FindCVar("wf_map_mlr").GetBool();
		
		if ( CVar.FindCVar("wf_intros").GetBool() )
		{
			if ( ( nextMap != "masterhub" && rejects) && nextMap != "lr_map08" && nextMap != "ja_map01"  && nextMap != "tn_map12"  && nextMap != "tn_map21" && nextMap != "pl_map12" && nextMap != "pl_map21" && nextMap != "ab_map12" && nextMap != "ab_map21" && nextMap != "dz_map01" && nextMap != "dz_map12" && nextMap != "dz_map21" && nextMap != "tr_map01" && nextMap != "tr_map12" && nextMap != "tr_map21" )
				Level.ChangeLevel("wf_story", 0, CHANGELEVEL_RESETINVENTORY|CHANGELEVEL_RESETHEALTH|CHANGELEVEL_NOINTERMISSION);
			else
				Level.ChangeLevel(nextMap, 0, CHANGELEVEL_RESETINVENTORY|CHANGELEVEL_RESETHEALTH|CHANGELEVEL_NOINTERMISSION);
		}
		else
			Level.ChangeLevel(nextMap, 0, CHANGELEVEL_RESETINVENTORY|CHANGELEVEL_RESETHEALTH|CHANGELEVEL_NOINTERMISSION);
		}

	void DCX_IntermissionStory()
	{
		string mapName = Level.MapName.MakeLower();
		
		if ( mapName.Left(8) == "wf_story" )
		{
			//Masterb_intro
			
			if ( nextMap == "ml_map19" )
					intermission = "MasterLevels_Map19";					
			if ( nextMap == "ml_map29" )
					intermission = "MasterLevels_Map29";
			if ( nextMap == "ml_map01" )
					intermission = "Masterb_intro";					
			if ( nextMap == "ml_map33" )
					intermission = "MasterLevels_Map33";			
			if ( mapName.Mid(9, 6) != "ml_map" )
			{
				// play episode intro stories
				if ( nextMap == "e1m1" )
					intermission = "Doom1_Intro";
				else if ( nextMap == "e2m1" )
					intermission = "Doom1_Intro_2";
				else if ( nextMap == "e3m1" )
					intermission = "Doom1_Intro_3";
				else if ( nextMap == "e4m1" )
					intermission = "Doom_Intro_4";
				else if ( nextMap == "e5m1" )
					intermission = "Sigil_Intro";
				else if ( nextMap == "e6m1" )
					intermission = "Sigil2_Intro";
				else if ( nextMap == "map01" )
					intermission = "Doom2_Intro";
				else if ( nextMap == "map12" )
					intermission = "Doom2_Intro_2";
				else if ( nextMap == "map21" )
					intermission = "Doom2_Intro_3";
				else if ( nextMap == "nv_map01" )
					intermission = "Nerve_Intro";
				else if ( nextMap == "lr_map01" )
					intermission = "Id1_Intro";
				else if ( nextMap == "tn_map01" )
					intermission = "Tnt_Intro";
				else if ( nextMap == "pl_map01" )
					intermission = "Plutonia_Intro";
				else if ( nextMap == "ab_map01" )
					intermission = "Absolution_Intro";
				else if ( nextMap == "tr_map01" )
					intermission = "TNTR_Intro";
				else if ( nextMap == "pt_map01" )
					intermission = "PT2_Intro";
				else if ( nextMap == "pg_map01" )
					intermission = "PG_Intro";
				else if ( nextMap == "le_e1m1" )
					intermission = "LostEpisode_Intro";
				else if ( Nextmap == "ka_map" )
					intermission = "KA_Intro";
				
				StoryStartIntermission();
				
				// don't skip the screen wipe when loading a newgame hack map
				int fullRun = CVar.FindCVar("wf_fullrun").GetInt();
				if ( fullRun >= 1 && fullRun <= 3 )
					fullRunNewGame = true;
				
				// change to the map which was set in NewGameIntro() or FullRun()
				if ( Level.MapTime >= 1 )
				{
					if ( !fullRunFinished )
						Level.ChangeLevel(nextMap, 0, CHANGELEVEL_RESETINVENTORY|CHANGELEVEL_RESETHEALTH|CHANGELEVEL_NOINTERMISSION);
					// try changing to a level that doesn't exist
					// this triggets the default ending sequence -- Fusion_GotoTitle
					else if ( !multiplayer )
						Level.ChangeLevel("", 0, CHANGELEVEL_NOINTERMISSION);
				}
			}
			else
			{
				// hack for adding optional story intermissions in the master levels rejects
				string mapSuffix = mapName.Mid(15, 2);
				intermission = "MasterLevels_Map"..mapSuffix;
				nextMap = "ml_map"..mapSuffix;
				
				StoryStartIntermission();
				
				if ( Level.MapTime >= 1 )
				{
					if ( mapSuffix == "29" || mapSuffix == "30" ||
						 mapSuffix == "31" || mapSuffix == "32" ||
						 mapSuffix == "16" || mapSuffix == "17" ||
						 mapSuffix == "33" || mapSuffix == "19" )
					{
						Level.ChangeLevel(nextMap, 0, CHANGELEVEL_RESETINVENTORY|CHANGELEVEL_RESETHEALTH|CHANGELEVEL_NOINTERMISSION);
					}
					else
						Level.ChangeLevel(nextMap, 0, CHANGELEVEL_NOINTERMISSION);
				}
			}
		}
	}
	
	void DCX_FullRun()
	{
		int fullRun = CVar.FindCVar("wf_fullrun").GetInt();
		int fullRunCast = CVar.FindCVar("wf_fullrun_cast").GetBool();
		let rejects = CVar.FindCVar("wf_map_mlr").GetBool();
		let titlePic = CVar.FindCVar("wf_compat_titlepics").GetBool();
		string mapName = Level.MapName.MakeLower();
		
		// set which intermission to play at the end of an episode
		if ( fullRun >= 1 && fullRun <= 3 )
		{
			if ( mapName == "e1m8" || mapName == "e1m8b" )
				intermission = "Doom1_Ep1_Fusion_FullRun";
			if ( mapName == "e2m8" )
				intermission = "Doom1_Ep2_Fusion_FullRun";
			if ( mapName == "e3m8" )
				intermission = "Inter_Bunny_Fusion_FullRun";
			if ( mapName == "wf_d1e4_ending" )
				intermission = "Doom1_Ep4_Fusion_FullRun_Alt";
			if ( mapName == "e4m8" )
				intermission = "Doom1_Ep4_Fusion_FullRun";
			if ( mapName == "psx05" )
				intermission = "Doom1_Ep4_Fusion_FullRun";
			if ( mapName == "e5m8" )
				intermission = "Doom1_Ep5_Fusion_FullRun";
			if ( mapName == "e6m8" )
				intermission = "Doom1_Ep6_Fusion_FullRun";
			if ( mapName == "map30" )
			{
				if ( fullRunCast )
					intermission = "Inter_Cast_Fusion_FullRun";
				else
					intermission = "Doom2_End_Fusion_FullRun_NoCast";
			}
			if ( mapName == "psx07" )
			{
				if ( fullRunCast )
					intermission = "Inter_Cast_Fusion_FullRun";
				else
					intermission = "Doom2_End_Fusion_FullRun_NoCast";
			}
			if ( ( mapName == "ml_map20" && !rejects ) || mapName == "ml_map43" )
			{
				if ( fullRunCast )
					intermission = "MasterLevels_End_Fusion_FullRun";
				else
					intermission = "MasterLevels_End_Fusion_FullRun_NoCast";
			}
			if ( mapName == "nv_map08" )
			{
				if ( fullRunCast )
					intermission = "Inter_Cast_Nerve_Fusion_FullRun";
				else
					intermission = "Nerve_End_Fusion_FullRun_NoCast";
			}
			if ( mapName == "lr_map07" )
				intermission = "Id1_Ep1_Fusion_FullRun";
			if ( mapName == "lr_map14" )
			{
				if ( fullRunCast )
					intermission = "Id1Cast_Fusion_FullRun";
				else
					intermission = "Id1_End_Fusion_FullRun_NoCast";
			}
			if ( mapName == "ab_map30" )
			{
				if ( fullRunCast )
					intermission = "D64Cast_Fusion_FullRun";
				else
					intermission = "D64_End_Fusion_FullRun_NoCast";
			}
			if ( mapName == "tn_map30" )
			{
				if ( fullRunCast )
					intermission = "Inter_Cast_Tnt_Fusion_FullRun";
				else
					intermission = "Tnt_End_Fusion_FullRun_NoCast";
			}
			if ( mapName == "pl_map30" )
			{
				if ( fullRunCast )
					intermission = "Inter_Cast_Plutonia_Fusion_FullRun";
				else
					intermission = "Plutonia_End_Fusion_FullRun_NoCast";
			}
		}
		// play a vanilla or vanilla-esque intermission if fullrun is off
		else
		{
			if ( mapName == "e1m8" || mapName == "e1m8b" )
				intermission = "Doom1_Ep1_Fusion_FullRun_Off";
			if ( mapName == "e2m8" )
				intermission = "Doom1_Ep2_Fusion_FullRun_Off";
			if ( mapName == "e3m8" )
				intermission = "Inter_Bunny_Fusion_FullRun_Off";
			if ( mapName == "wf_d1e4_ending" )
				intermission = "Doom1_Ep4_Fusion_FullRun_Alt_Off";
			if ( mapName == "e4m8" )
				intermission = "Doom1_Ep4_Fusion_FullRun_Off";
			if ( mapName == "psx05" )
				intermission = "Doom1_Ep4_Fusion_FullRun_Off";
			if ( mapName == "e5m8" )
				intermission = "Doom1_Ep5_Fusion_FullRun_Off";
			if ( mapName == "e6m8" )
				intermission = "Doom1_Ep6_Fusion_FullRun_Off";
			if ( mapName == "map30" )
				intermission = "Inter_Cast";
			if ( ( mapName == "ml_map20" && !rejects ) || mapName == "ml_map27")
				intermission = "MasterLevels_End"; // also needed for xaser order
			if ( mapName == "ml_map32" && rejects )
				intermission = "MasterLevels_End_Map32";
			if ( mapName == "ml_map36" )
				intermission = "MasterLevels_End_Map36";
			if ( mapName == "ml_map43" )
				intermission = "MasterLevels_End_Map43";
			if ( mapName == "nv_map08" )
				intermission = "Nerve_Cast";
			if ( mapName == "lr_map07" )
				intermission = "Id1_Ep1_Fusion_FullRun_Off";
			if ( mapName == "lr_map14" )
				intermission = "Id1Cast";
			if ( mapName == "ab_map30" )
				intermission = "D64Cast";
			if ( mapName == "tn_map30" )
				intermission = "Inter_Cast_Tnt";
			if ( mapName == "pl_map30" )
				intermission = "Inter_Cast_Plutonia";
		}
		
		// set which map to switch to at the end of a full run episode
		if ( fullRun == 1 )
		{
			if ( mapName == "e1m8" || mapName == "e1m8b" )
				nextMap = "e2m1";
			if ( mapName == "e2m8" )
			{
				if ( CVar.GetCvar("dcx_playstationmaps").getint() == 2 )
				{	if ( Wads.CheckNumForFullName("maps/psx02b.wad") != -1 )
					nextMap = "psx02b";	}
				else if ( CVar.GetCvar("dcx_playstationmaps").getint() == 1 )
				{	if ( Wads.CheckNumForFullName("maps/psx02.wad") != -1 )
					nextMap = "psx02";	}
				else
				{	NextMap = "e3m1"; }
			}
			if ( mapName == "e3m8" )
			{
				if ( Wads.CheckNumForFullName("maps/e4m1.wad") != -1 )
					nextMap = "wf_newgame_e4m1";
				else if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/map01.wad") != -1 )
					nextMap = "wf_newgame_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else if ( Wads.CheckNumForFullName("maps/ab_map01.wad") != -1 )
					nextMap = "wf_newgame_ab_map01";
				else if ( Wads.CheckNumForFullName("maps/dz_map01.wad") != -1 )
					nextMap = "wf_newgame_dz_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/tr_map01.wad") != -1 )
					nextMap = "wf_newgame_tr_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "wf_d1e4_ending" )
			{
				if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/map01.wad") != -1 )
					nextMap = "wf_newgame_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else if ( Wads.CheckNumForFullName("maps/ab_map01.wad") != -1 )
					nextMap = "wf_newgame_ab_map01";
				else if ( Wads.CheckNumForFullName("maps/dz_map01.wad") != -1 )
					nextMap = "wf_newgame_dz_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/tr_map01.wad") != -1 )
					nextMap = "wf_newgame_tr_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "e4m8" )
			{
				if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/map01.wad") != -1 )
					nextMap = "wf_newgame_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else if ( Wads.CheckNumForFullName("maps/ab_map01.wad") != -1 )
					nextMap = "wf_newgame_ab_map01";
				else if ( Wads.CheckNumForFullName("maps/dz_map01.wad") != -1 )
					nextMap = "wf_newgame_dz_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/tr_map01.wad") != -1 )
					nextMap = "wf_newgame_tr_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "psx05" )
			{
				if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/map01.wad") != -1 )
					nextMap = "wf_newgame_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else if ( Wads.CheckNumForFullName("maps/ab_map01.wad") != -1 )
					nextMap = "wf_newgame_ab_map01";
				else if ( Wads.CheckNumForFullName("maps/dz_map01.wad") != -1 )
					nextMap = "wf_newgame_dz_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/tr_map01.wad") != -1 )
					nextMap = "wf_newgame_tr_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "e5m8" )
			{
				if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/map01.wad") != -1 )
					nextMap = "wf_newgame_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else if ( Wads.CheckNumForFullName("maps/ab_map01.wad") != -1 )
					nextMap = "wf_newgame_ab_map01";
				else if ( Wads.CheckNumForFullName("maps/dz_map01.wad") != -1 )
					nextMap = "wf_newgame_dz_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/tr_map01.wad") != -1 )
					nextMap = "wf_newgame_tr_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "e6m8" )
			{
				if ( Wads.CheckNumForFullName("maps/map01.wad") != -1 )
					nextMap = "wf_newgame_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else if ( Wads.CheckNumForFullName("maps/ab_map01.wad") != -1 )
					nextMap = "wf_newgame_ab_map01";
				else if ( Wads.CheckNumForFullName("maps/dz_map01.wad") != -1 )
					nextMap = "wf_newgame_dz_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/tr_map01.wad") != -1 )
					nextMap = "wf_newgame_tr_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "map30" || mapName == "psx07" )
			{
				if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else if ( Wads.CheckNumForFullName("maps/ab_map01.wad") != -1 )
					nextMap = "wf_newgame_ab_map01";
				else if ( Wads.CheckNumForFullName("maps/dz_map01.wad") != -1 )
					nextMap = "wf_newgame_dz_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/tr_map01.wad") != -1 )
					nextMap = "wf_newgame_tr_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "nv_map08" )
			{
				if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else if ( Wads.CheckNumForFullName("maps/ab_map01.wad") != -1 )
					nextMap = "wf_newgame_ab_map01";
				else if ( Wads.CheckNumForFullName("maps/dz_map01.wad") != -1 )
					nextMap = "wf_newgame_dz_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/tr_map01.wad") != -1 )
					nextMap = "wf_newgame_tr_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "lr_map07" )
			{
				nextMap = "lr_map08";
			}
			if ( mapName == "lr_map14" )
			{
				if ( Wads.CheckNumForFullName("maps/ab_map01.wad") != -1 )
					nextMap = "wf_newgame_ab_map01";
				else if ( Wads.CheckNumForFullName("maps/dz_map01.wad") != -1 )
					nextMap = "wf_newgame_dz_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/tr_map01.wad") != -1 )
					nextMap = "wf_newgame_tr_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "ab_map30" )
			{
				if ( Wads.CheckNumForFullName("maps/dz_map01.wad") != -1 )
					nextMap = "wf_newgame_dz_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/tr_map01.wad") != -1 )
					nextMap = "wf_newgame_tr_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "dz_map30" )
			{
				if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/tr_map01.wad") != -1 )
					nextMap = "wf_newgame_tr_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( ( mapName == "ml_map20" && !rejects ) || mapName == "ml_map43" )
			{
				if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/tr_map01.wad") != -1 )
					nextMap = "wf_newgame_tr_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "tn_map30" )
			{
				if ( Wads.CheckNumForFullName("maps/tr_map01.wad") != -1 )
					nextMap = "wf_newgame_tr_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "tr_map30" )
			{
				if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "pl_map30" )
			{
				if ( Wads.CheckNumForFullName("maps/pt_map01.wad") != -1 )
					nextMap = "wf_newgame_pt_map01";
				else if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
				FullRunEnd();
			}
			if ( mapName == "pt_map30" )
			{
				if ( Wads.CheckNumForFullName("maps/le_e1m1.wad") != -1 )
					nextMap = "wf_newgame_le_e1m1";
				else if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "le_e1m8" )
			{
				nextMap = "le_e2m1";
			}
			if ( mapName == "le_e2m8" )
			{
				nextMap = "le_e3m1";
			}
			if ( mapName == "le_e3m8" )
			{
				if ( Wads.CheckNumForFullName("maps/pg_map01.wad") != -1 )
					nextMap = "wf_newgame_pg_map01";
				else if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "pg_map30" )
			{
				if ( Wads.CheckNumForFullName("maps/hp_map01.wad") != -1 )
					nextMap = "wf_newgame_hp_map01";
				else
					FullRunEnd();
			}
			if ( mapName == "hp_map30" )
				FullRunEnd();
		}
		if ( fullRun == 2 )
		{
			if ( mapName == "e1m8" || mapName == "e1m8b" )
				nextMap = "e2m1";
			if ( mapName == "e2m8" )
			{
				if ( CVar.GetCvar("dcx_playstationmaps").getint() == 2 )
				{	NextMap = "PSX02B";	}
				else if ( CVar.GetCvar("dcx_playstationmaps").getint() == 1 )
				{	NextMap = "PSX02";	}
				else
				{	NextMap = "e3m1"; }
			}
			if ( mapName == "e3m8" )
				if ( Wads.CheckNumForFullName("maps/map01.wad") != -1 )
					nextMap = "wf_newgame_map01";
				else if ( Wads.CheckNumForFullName("maps/e4m1.wad") != -1 )
					nextMap = "wf_newgame_e4m1";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "map30" || mapName == "psx07" )
				if ( Wads.CheckNumForFullName("maps/e4m1.wad") != -1 )
					nextMap = "wf_newgame_e4m1";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "wf_d1e4_ending" )
				if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "e4m8" )
				if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "psx05" )
				if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();			
			if ( ( mapName == "ml_map20" && !rejects ) || mapName == "ml_map43" )
				if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "tn_map30" )
				if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "pl_map30" )
				if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "nv_map08" )
				if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "e5m8" )
				if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "e6m8" )
				if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "lr_map07" )
				nextMap = "lr_map08";
			if ( mapName == "lr_map14" )
					FullRunEnd();
			}
		if ( fullRun == 3 )
		{
			if ( mapName == "e1m8" || mapName == "e1m8b" )
				nextMap = "e2m1";
			if ( mapName == "e2m8" )
			{
				if ( CVar.GetCvar("dcx_playstationmaps").getint() == 2 )
				{	NextMap = "PSX02B";	}
				else if ( CVar.GetCvar("dcx_playstationmaps").getint() == 1 )
				{	NextMap = "PSX02";	}
				else
				{	NextMap = "e3m1"; }
			}
			if ( mapName == "e3m8" )
				if ( Wads.CheckNumForFullName("maps/e4m1.wad") != -1 )
					nextMap = "wf_newgame_e4m1";
				else if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/map01.wad") != -1 )
					nextMap = "wf_newgame_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "wf_d1e4_ending" )
				if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/map01.wad") != -1 )
					nextMap = "wf_newgame_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "e4m8" )
				if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/map01.wad") != -1 )
					nextMap = "wf_newgame_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "psx05" )
				if ( Wads.CheckNumForFullName("maps/e5m1.wad") != -1 )
					nextMap = "wf_newgame_e5m1";
				else if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/map01.wad") != -1 )
					nextMap = "wf_newgame_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "e5m8" )
				if ( Wads.CheckNumForFullName("maps/e6m1.wad") != -1 )
					nextMap = "wf_newgame_e6m1";
				else if ( Wads.CheckNumForFullName("maps/map01.wad") != -1 )
					nextMap = "wf_newgame_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "e6m8" )
				if ( Wads.CheckNumForFullName("maps/map01.wad") != -1 )
					nextMap = "wf_newgame_map01";
				else if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "map30" )
				if ( Wads.CheckNumForFullName("maps/nv_map01.wad") != -1 )
					nextMap = "wf_newgame_nv_map01";
				else if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "nv_map08" )
				if ( Wads.CheckNumForFullName("maps/ml_map01.wad") != -1 )
					nextMap = "wf_newgame_ml_map01";
				else if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( ( mapName == "ml_map20" && !rejects ) || mapName == "ml_map43" )
				if ( Wads.CheckNumForFullName("maps/tn_map01.wad") != -1 )
					nextMap = "wf_newgame_tn_map01";
				else if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "tn_map30" )
				if ( Wads.CheckNumForFullName("maps/pl_map01.wad") != -1 )
					nextMap = "wf_newgame_pl_map01";
				else if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "pl_map30" )
				if ( Wads.CheckNumForFullName("maps/lr_map01.wad") != -1 )
					nextMap = "wf_newgame_lr_map01";
				else
					FullRunEnd();
			if ( mapName == "lr_map07" )
				nextMap = "lr_map08";
			if ( mapName == "lr_map14" )
				FullRunEnd();
		}
	}
}