//
Extend Class DCX_EventHandler
{
	void DCX_AddMasterLevelsRejects() //Modify this so that when rejects are disabled, that the master levels episode takes you to the normal master levels campaign.
	{
		let rejects = CVar.FindCVar("wf_map_mlr").GetBool();
		let rejectsStory = CVar.FindCVar("wf_map_mlr_story").GetBool();
		string mapName = Level.MapName.MakeLower();
		
		if ( mapName == "ml_map02" )
		{
			if ( rejects )
				Level.NextMap = "ml_map28";
			else
				Level.NextMap = "ml_map03";
		}
		
		if ( mapName == "ml_map03" )
		{
			if ( rejects )
				Level.NextMap = "ml_map25";
			else
				Level.NextMap = "ml_map04";
		}
		
		if ( mapName == "ml_map04" )
		{
			if ( rejects )
				Level.NextMap = "ml_map08";
			else
				Level.NextMap = "ml_map05";
		}
		
		if ( mapName == "ml_map05" )
		{
			if ( rejects )
				Level.NextMap = "ml_map23";
			else
				Level.NextMap = "ml_map06";
		}
		
		if ( mapName == "ml_map06" )
		{
			if ( rejects )
				Level.NextMap = "ml_map05";
			else
				Level.NextMap = "ml_map07";
		}
		
		if ( mapName == "ml_map07" )
		{
			if ( rejects )
				Level.NextMap = "ml_map22";
			else
				Level.NextMap = "ml_map08";
		}
		
		if ( mapName == "ml_map08" )
		{
			if ( rejects )
				Level.NextMap = "ml_map24";
			else
				Level.NextMap = "ml_map09";
		}
		
		if ( mapName == "ml_map09" )
		{
			if ( rejects )
				Level.NextMap = "ml_map26";
			else
				Level.NextMap = "ml_map10";
		}
		
		if ( mapName == "ml_map10" )
		{
			if ( !rejects )
				Level.NextMap = "ml_map11";
		}
		
		if ( mapName == "ml_map11" )
		{
			if ( !rejects )
				Level.NextMap = "ml_map12";
		}
		
		if ( mapName == "ml_map17" )
		{
			if ( !rejects )
				Level.NextMap = "ml_map18";
			else
				Level.NextMap = "wf_story_ml_map32";
		}
		
		if ( mapName == "ml_map19" )
		{
			if ( rejects )
			{
				if ( rejectsStory )
					Level.NextMap = "wf_story_ml_map38";
				else
					Level.NextMap = "ml_map38";
			}
			else
				Level.NextMap = "ml_map20";
		}
		
		if ( mapName == "ml_map32" || mapName == "ml_map27" || mapName == "ml_map36" )
		{
			Level.NextMap = "wf_story";
		}
		
		if ( mapName == "ml_map31" )
		{
			Level.NextMap = "wf_story_ml_map16";
		}
		
		if ( mapName == "ml_map37" )
		{
			Level.NextMap = "ml_map39";
		}
		
		if ( mapName == "ml_map38" )
		{
			if ( rejectsStory )
				Level.NextMap = "wf_story_ml_map37";
			else
				Level.NextMap = "ml_map37";
		}
		
		/*
		if ( mapName == "ml_map02" )
		{
			if ( rejects )
				Level.NextMap = "ml_map45";
			else
				Level.NextMap = "ml_map03";
		}
		if ( mapName == "ml_map06" )
		{
			if ( rejects )
				Level.NextMap = "ml_map08";
			else
				Level.NextMap = "ml_map07";
		}
		if ( mapName == "ml_map09" )
		{
			if ( rejects )
				Level.NextMap = "ml_map22";
			else
				Level.NextMap = "ml_map10";
		}
		if ( mapName == "ml_map07" )
		{
			if ( rejects )
			{
				if ( rejectsStory )
					Level.NextMap = "wf_story_ml_map29";
				else
					Level.NextMap = "ml_map29";
			}
			else
				Level.NextMap = "ml_map08";
		}
		if ( mapName == "ml_map17" )
		{
			if ( rejects )
			{
				if ( rejectsStory )
					Level.NextMap = "wf_story_ml_map33";
				else
					Level.NextMap = "ml_map33";
			}
			else
				Level.NextMap = "ml_map18";
		}
		if ( mapName == "ml_map15" )
		{
			if ( rejects )
				Level.NextMap = "ml_map35";
			else
				Level.NextMap = "ml_map16";
		}
		if ( mapName == "ml_map19" )
		{
			if ( rejects )
			{
				if ( rejectsStory )
					Level.NextMap = "wf_story_ml_map37";
				else
					Level.NextMap = "ml_map37";
			}
			else
				Level.NextMap = "ml_map20";
		}
		if ( mapName == "ml_map20" )
		{
			if ( rejects )
				Level.NextMap = "ml_map40";
			else
				Level.NextMap = "wf_story";
		}
		if ( mapName == "ml_map18" || mapName == "ml_map21" )
		{
			if ( rejects )
			{
				if ( rejectsStory )
					Level.NextMap = "wf_story_ml_map41";
				else
					Level.NextMap = "ml_map41";
			}
			else
				Level.NextMap = "ml_map19";
		}
		if ( mapName == "ml_map10" )
		{
			if ( rejects )
				if ( rejectsStory )
					Level.NextMap = "wf_story_ml_map43";
				else
					Level.NextMap = "ml_map43";
			else
				Level.NextMap = "ml_map11";
		}
		
		if ( mapName == "ml_map29" )
		{
			if ( rejectsStory )
				Level.NextMap = "wf_story_ml_map30";
			else
				Level.NextMap = "ml_map30";
		}
		if ( mapName == "ml_map30" )
		{
			if ( rejectsStory )
				Level.NextMap = "wf_story_ml_map31";
			else
				Level.NextMap = "ml_map31";
		}
		if ( mapName == "ml_map31" )
		{
			if ( rejectsStory )
				Level.NextMap = "wf_story_ml_map32";
			else
				Level.NextMap = "ml_map32";
		}
		if ( mapName == "ml_map32" )
		{
			if ( rejectsStory )
				Level.NextMap = "wf_story_ml_map16";
			else
				Level.NextMap = "ml_map16";
		}
		if ( mapName == "ml_map16" )
		{
			if ( rejects && rejectsStory )
				Level.NextMap = "wf_story_ml_map17";
			else
				Level.NextMap = "ml_map17";
		}
		if ( mapName == "ml_map33" )
		{
			if ( rejectsStory )
				Level.NextMap = "wf_story_ml_map34";
			else
				Level.NextMap = "ml_map34";
		}
		if ( mapName == "ml_map34" )
		{
			if ( rejectsStory )
				Level.NextMap = "wf_story_ml_map11";
			else
				Level.NextMap = "ml_map11";
		}
		if ( mapName == "ml_map11" )
		{
			if ( rejects && rejectsStory )
				Level.NextMap = "wf_story_ml_map12";
			else
				Level.NextMap = "ml_map12";
		}
		if ( mapName == "ml_map12" )
		{
			if ( rejects && rejectsStory )
				Level.NextMap = "wf_story_ml_map13";
			else
				Level.NextMap = "ml_map13";
		}
		if ( mapName == "ml_map14" )
		{
			if ( rejects && rejectsStory )
				Level.NextMap = "wf_story_ml_map15";
			else
				Level.NextMap = "ml_map15";
		}
		if ( mapName == "ml_map36" )
		{
			if ( rejectsStory )
				Level.NextMap = "wf_story_ml_map19";
			else
				Level.NextMap = "ml_map19";
		}
		if ( mapName == "ml_map37" )
		{
			if ( rejectsStory )
				Level.NextMap = "wf_story_ml_map38";
			else
				Level.NextMap = "ml_map38";
		}
		if ( mapName == "ml_map39" )
		{
			if ( rejectsStory )
				Level.NextMap = "wf_story_ml_map20";
			else
				Level.NextMap = "ml_map20";
		}
		if ( mapName == "ml_map40" )
		{
			if ( rejectsStory )
				Level.NextMap = "wf_story_ml_map18";
			else
				Level.NextMap = "ml_map18";
		}
		if ( mapName == "ml_map41" )
		{
			if ( rejectsStory )
				Level.NextMap = "wf_story_ml_map42";
			else
				Level.NextMap = "ml_map42";
		}
		if ( mapName == "ml_map42" )
		{
			if ( rejectsStory )
				Level.NextMap = "wf_story_ml_map10";
			else
				Level.NextMap = "ml_map10";
		}
		*/
	}
}